apiVersion: v1
kind: Service
metadata:
  name: {{ include "zke.server.fullname" . }}
  annotations:
    {{- toYaml .Values.server.service.annotations | nindent 4 }}
  labels:
    {{- include "zke.labels" . | nindent 4 }}
    {{- include "zke.server.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "zke.server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: pod-access
      port: {{ .Values.server.service.podAccessPort }}
      targetPort: pod-access
      protocol: TCP
    - name: agent-quic
      port: {{ .Values.server.service.agentQUICPort }}
      targetPort: agent-quic
      protocol: UDP
