/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeCurrentUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get: operations["getUser"];
        put: operations["updateUser"];
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setUserStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unlockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoleBindings"];
        put?: never;
        post: operations["createRoleBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role-bindings/{role_binding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRoleBinding"];
        put?: never;
        post?: never;
        delete: operations["deleteRoleBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 发送 `ready`、`cluster.status` 和 `close` 事件以及注释心跳。
         *     断线重连后客户端应重新查询 Cluster 状态；当前不承诺历史事件重放。
         */
        get: operations["streamClusterStatusEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenants"];
        put?: never;
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        get: operations["getTenant"];
        put: operations["updateTenant"];
        post?: never;
        delete: operations["deleteTenant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCluster"];
        put: operations["updateCluster"];
        post?: never;
        delete: operations["deleteCluster"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/cluster-enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listClusterEnrollments"];
        put?: never;
        post: operations["createClusterEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/cluster-enrollments/{enrollment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectID"];
                enrollment_id: components["parameters"]["EnrollmentID"];
            };
            cookie?: never;
        };
        get: operations["getClusterEnrollment"];
        put?: never;
        post?: never;
        delete: operations["revokeClusterEnrollment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/cluster-installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createClusterInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{cluster_id}/connection/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeClusterConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{cluster_id}/connection/reenroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reenrollClusterConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-api/v1/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enrollAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-install/v1/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgentInstallationManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        /**
         * Format: date-time
         * @example 2026-07-26T14:30:00+08:00
         */
        Timestamp: string;
        SuccessResponse: {
            code: number;
            /** @constant */
            message: "Success";
        };
        ErrorData: {
            error_code: string;
            request_id: string;
        };
        Error: {
            code: number;
            message: string;
            data: components["schemas"]["ErrorData"];
        };
        Health: {
            [key: string]: unknown;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        Authentication: {
            user: components["schemas"]["UserIdentity"];
            expires_at: components["schemas"]["Timestamp"];
        };
        CurrentSession: {
            user: components["schemas"]["UserIdentity"];
            expires_at: components["schemas"]["Timestamp"];
            capabilities: components["schemas"]["Capability"][];
        };
        Capability: {
            /** @enum {string} */
            role: "admin" | "viewer";
            /** @enum {string} */
            scope_type: "global" | "tenant" | "project";
            tenant_id?: components["schemas"]["UUID"];
            project_id?: components["schemas"]["UUID"];
            permissions: ("tenant.create" | "tenant.read" | "tenant.manage" | "project.create" | "project.read" | "project.manage" | "cluster.enrollment.create" | "cluster.enrollment.read" | "cluster.enrollment.revoke" | "cluster.read" | "cluster.manage" | "cluster.connection.revoke" | "user.read" | "user.manage" | "rbac.read" | "rbac.manage" | "audit.read")[];
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
            /** @constant */
            confirm: true;
        };
        UserIdentity: {
            id: components["schemas"]["UUID"];
            username: string;
            display_name: string;
        };
        ManagedUser: components["schemas"]["UserIdentity"] & {
            /** @enum {string} */
            status: "active" | "locked" | "disabled";
            failed_login_count: number;
            locked_at?: components["schemas"]["Timestamp"];
            lock_expires_at?: components["schemas"]["Timestamp"];
            password_changed_at: components["schemas"]["Timestamp"];
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        CreateUserRequest: {
            username: string;
            display_name: string;
            /** Format: password */
            password: string;
        };
        UpdateUserRequest: {
            display_name: string;
        };
        SetUserStatusRequest: {
            /** @enum {string} */
            status: "active" | "disabled";
            /** @constant */
            confirm: true;
        };
        Confirmation: {
            /** @constant */
            confirm: true;
        };
        UpdateScopedResourceRequest: {
            name: string;
            /** @enum {string} */
            status: "active" | "suspended";
            /** @description status=suspended 时必须为 true */
            confirm: boolean;
        };
        UpdateClusterRequest: {
            name: string;
        };
        PasswordResetRequest: {
            /** Format: password */
            password: string;
            /** @constant */
            confirm: true;
        };
        RoleBinding: {
            id: components["schemas"]["UUID"];
            subject_id: components["schemas"]["UUID"];
            /** @enum {string} */
            role: "admin" | "viewer";
            /** @enum {string} */
            scope_type: "global" | "tenant" | "project";
            tenant_id?: components["schemas"]["UUID"];
            project_id?: components["schemas"]["UUID"];
            created_at: components["schemas"]["Timestamp"];
            replayed?: boolean;
        };
        CreateRoleBindingRequest: {
            subject_id: components["schemas"]["UUID"];
            /** @enum {string} */
            role: "admin" | "viewer";
            /** @enum {string} */
            scope_type: "global" | "tenant" | "project";
            tenant_id?: components["schemas"]["UUID"];
            project_id?: components["schemas"]["UUID"];
            /** @constant */
            confirm: true;
        };
        ResourceBase: {
            id: components["schemas"]["UUID"];
            name: string;
            status: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            replayed?: boolean;
        };
        Pagination: {
            limit: number;
            offset: number;
            total: number;
            has_more: boolean;
        };
        Tenant: components["schemas"]["ResourceBase"];
        Project: components["schemas"]["ResourceBase"] & {
            tenant_id: components["schemas"]["UUID"];
        };
        Cluster: components["schemas"]["ResourceBase"] & {
            tenant_id: components["schemas"]["UUID"];
            project_id: components["schemas"]["UUID"];
            last_seen_at?: components["schemas"]["Timestamp"];
        };
        ClusterConnection: {
            /** @enum {string} */
            status: "online" | "offline";
            lifecycle_status: string;
            health_status: string;
            version: string;
            protocol_version: string;
            last_seen_at?: components["schemas"]["Timestamp"];
            certificate_serial: string;
            certificate_expires_at: components["schemas"]["Timestamp"];
            certificate_remaining_seconds: number;
            /** @enum {string} */
            certificate_status: "valid" | "expiring" | "expired" | "revoked";
            connection_id?: string;
            connected_at?: components["schemas"]["Timestamp"];
            last_heartbeat_at?: components["schemas"]["Timestamp"];
            last_disconnected_at?: components["schemas"]["Timestamp"];
            last_disconnect_reason?: string;
        };
        ClusterAggregate: components["schemas"]["Cluster"] & {
            connection: components["schemas"]["ClusterConnection"];
        };
        ClusterEnrollment: {
            id: components["schemas"]["UUID"];
            cluster_id?: components["schemas"]["UUID"];
            cluster_name: string;
            token: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        ClusterEnrollmentRecord: {
            id: components["schemas"]["UUID"];
            tenant_id: components["schemas"]["UUID"];
            project_id: components["schemas"]["UUID"];
            cluster_id?: components["schemas"]["UUID"];
            cluster_name: string;
            created_by_user_id: components["schemas"]["UUID"];
            /** @enum {string} */
            status: "active" | "consumed" | "expired" | "revoked";
            expires_at: components["schemas"]["Timestamp"];
            consumed_at?: components["schemas"]["Timestamp"];
            revoked_at?: components["schemas"]["Timestamp"];
            created_at: components["schemas"]["Timestamp"];
        };
        ClusterInstallation: {
            id: components["schemas"]["UUID"];
            cluster_name: string;
            expires_at: components["schemas"]["Timestamp"];
            /** Format: uri */
            manifest_url: string;
            install_command: string;
        };
        ClusterConnectionRevocation: {
            cluster_id: components["schemas"]["UUID"];
            /** @constant */
            connection_status: "revoked";
            revoked_at: components["schemas"]["Timestamp"];
            already_revoked: boolean;
        };
        AgentEnrollmentRequest: {
            /** @description PEM 编码的 ECDSA P-256 PKCS#10 CSR */
            csr_pem: string;
            agent_version: string;
            /** @constant */
            protocol_version: "v1";
        };
        AgentEnrollmentResponse: {
            cluster_id: components["schemas"]["UUID"];
            agent_id: components["schemas"]["UUID"];
            certificate_pem: string;
            certificate_expires_at: components["schemas"]["Timestamp"];
        };
        AuditEvent: {
            id: components["schemas"]["UUID"];
            /** @enum {string} */
            actor_type: "user" | "agent" | "system";
            actor_user_id?: components["schemas"]["UUID"];
            actor_agent_id?: components["schemas"]["UUID"];
            /** @enum {string} */
            scope_type: "global" | "tenant" | "project" | "cluster";
            tenant_id?: components["schemas"]["UUID"];
            project_id?: components["schemas"]["UUID"];
            cluster_id?: components["schemas"]["UUID"];
            action: string;
            target_type: string;
            target_id?: components["schemas"]["UUID"];
            /** @enum {string} */
            result: "succeeded" | "failed" | "denied";
            request_id: string;
            created_at: components["schemas"]["Timestamp"];
        };
        AuditEventPage: {
            audit_events: components["schemas"]["AuditEvent"][];
            next_cursor: string;
        };
    };
    responses: {
        /** @description 输入无效 */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证或 Session 已失效 */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description CSRF 或权限检查失败 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 目标不存在或不可见 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 幂等、生命周期或安全不变量冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求被限流 */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务暂不可用 */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求处理超时 */
        Timeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CSRFToken: string;
        IdempotencyKey: string;
        UserID: components["schemas"]["UUID"];
        RoleBindingID: components["schemas"]["UUID"];
        TenantID: components["schemas"]["UUID"];
        ProjectID: components["schemas"]["UUID"];
        ClusterID: components["schemas"]["UUID"];
        EnrollmentID: components["schemas"]["UUID"];
        OptionalTenantID: components["schemas"]["UUID"];
        OptionalProjectID: components["schemas"]["UUID"];
        OptionalClusterID: components["schemas"]["UUID"];
        Limit: number;
        ListLimit: number;
        ListOffset: number;
        ListSearch: string;
    };
    requestBodies: {
        CreateNamedResource: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Health"];
                    };
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server 已就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Health"];
                    };
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功；Session 和 CSRF Token 通过 Cookie 返回 */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Authentication"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前身份 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["CurrentSession"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已注销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    changeCurrentUserPassword: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 密码已修改，当前用户全部 Session 已撤销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: null;
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["ListLimit"];
                offset?: components["parameters"]["ListOffset"];
                q?: components["parameters"]["ListSearch"];
                status?: "active" | "locked" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: {
                            users: components["schemas"]["ManagedUser"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description 用户已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ManagedUser"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ManagedUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description 用户资料已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ManagedUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description 用户已逻辑删除并撤销全部 Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ManagedUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    setUserStatus: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUserStatusRequest"];
            };
        };
        responses: {
            /** @description 用户状态已更新，禁用会撤销现有 Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ManagedUser"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    unlockUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description 锁定计数已清除，账户恢复为 active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ManagedUser"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description 密码已重置，目标用户全部 Session 已撤销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ManagedUser"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listRoleBindings: {
        parameters: {
            query?: {
                limit?: components["parameters"]["ListLimit"];
                offset?: components["parameters"]["ListOffset"];
                q?: components["parameters"]["ListSearch"];
                role?: "admin" | "viewer";
                scope_type?: "global" | "tenant" | "project";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RoleBinding 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: {
                            role_bindings: components["schemas"]["RoleBinding"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createRoleBinding: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleBindingRequest"];
            };
        };
        responses: {
            /** @description 相同 RoleBinding 已存在 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["RoleBinding"];
                    };
                };
            };
            /** @description RoleBinding 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["RoleBinding"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_binding_id: components["parameters"]["RoleBindingID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RoleBinding 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["RoleBinding"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteRoleBinding: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                role_binding_id: components["parameters"]["RoleBindingID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description RoleBinding 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: null;
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: string;
                actor_type?: "user" | "agent" | "system";
                result?: "succeeded" | "failed" | "denied";
                action?: string;
                target_type?: string;
                request_id?: string;
                tenant_id?: components["parameters"]["OptionalTenantID"];
                project_id?: components["parameters"]["OptionalProjectID"];
                cluster_id?: components["parameters"]["OptionalClusterID"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 `audit.read` 可见范围内的审计事件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["AuditEventPage"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    streamClusterStatusEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster 状态事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            503: components["responses"]["Unavailable"];
        };
    };
    listTenants: {
        parameters: {
            query?: {
                limit?: components["parameters"]["ListLimit"];
                offset?: components["parameters"]["ListOffset"];
                q?: components["parameters"]["ListSearch"];
                status?: "active" | "suspended";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可见 Tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: {
                            tenants: components["schemas"]["Tenant"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateNamedResource"];
        responses: {
            /** @description 幂等恢复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Tenant"];
                    };
                };
            };
            /** @description Tenant 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Tenant"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Tenant"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTenant: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScopedResourceRequest"];
            };
        };
        responses: {
            /** @description Tenant 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Tenant"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteTenant: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description Tenant 已停用，下属接入身份已撤销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Tenant"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["ListLimit"];
                offset?: components["parameters"]["ListOffset"];
                q?: components["parameters"]["ListSearch"];
                status?: "active" | "suspended";
            };
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可见 Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: {
                            projects: components["schemas"]["Project"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateNamedResource"];
        responses: {
            /** @description 幂等恢复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            /** @description Project 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScopedResourceRequest"];
            };
        };
        responses: {
            /** @description Project 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description Project 已停用，下属接入身份已撤销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listClusters: {
        parameters: {
            query?: {
                limit?: components["parameters"]["ListLimit"];
                offset?: components["parameters"]["ListOffset"];
                q?: components["parameters"]["ListSearch"];
                status?: "pending" | "active" | "revoked";
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project Cluster 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: {
                            clusters: components["schemas"]["ClusterAggregate"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: components["parameters"]["ClusterID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ClusterAggregate"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCluster: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                cluster_id: components["parameters"]["ClusterID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClusterRequest"];
            };
        };
        responses: {
            /** @description Cluster 名称已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Cluster"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteCluster: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                cluster_id: components["parameters"]["ClusterID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description Cluster 已退役，内部接入身份和凭证已撤销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["Cluster"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listClusterEnrollments: {
        parameters: {
            query?: {
                limit?: components["parameters"]["ListLimit"];
                offset?: components["parameters"]["ListOffset"];
                q?: components["parameters"]["ListSearch"];
                status?: "active" | "consumed" | "expired" | "revoked";
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster Enrollment 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: {
                            cluster_enrollments: components["schemas"]["ClusterEnrollmentRecord"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createClusterEnrollment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cluster_name: string;
                };
            };
        };
        responses: {
            /** @description 一次性注册凭证 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ClusterEnrollment"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getClusterEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectID"];
                enrollment_id: components["parameters"]["EnrollmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster Enrollment 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ClusterEnrollmentRecord"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    revokeClusterEnrollment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                project_id: components["parameters"]["ProjectID"];
                enrollment_id: components["parameters"]["EnrollmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description Cluster Enrollment 已撤销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ClusterEnrollmentRecord"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    createClusterInstallation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cluster_name: string;
                };
            };
        };
        responses: {
            /** @description 安装命令 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ClusterInstallation"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["Timeout"];
        };
    };
    revokeClusterConnection: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                cluster_id: components["parameters"]["ClusterID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description Cluster 当前接入身份已撤销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ClusterConnectionRevocation"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reenrollClusterConnection: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cluster_id: components["parameters"]["ClusterID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirmation"];
            };
        };
        responses: {
            /** @description 原 Cluster 的新一次性接入凭证 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["ClusterEnrollment"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    enrollAgent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentEnrollmentRequest"];
            };
        };
        responses: {
            /** @description 幂等恢复的 Agent 身份 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["AgentEnrollmentResponse"];
                    };
                };
            };
            /** @description 新签发的 Agent 身份 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data: components["schemas"]["AgentEnrollmentResponse"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["Timeout"];
        };
    };
    getAgentInstallationManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kubernetes 多文档 YAML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["Timeout"];
        };
    };
}
