// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.21.11
// source: api/agent/v1/control.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_control_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_api_agent_v1_control_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{0}
}

type ControlFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControlFrame_ClientHello
	//	*ControlFrame_ServerHello
	//	*ControlFrame_Heartbeat
	//	*ControlFrame_HeartbeatAck
	//	*ControlFrame_ClientGoodbye
	//	*ControlFrame_GoAway
	Message       isControlFrame_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame) Reset() {
	*x = ControlFrame{}
	mi := &file_api_agent_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame) ProtoMessage() {}

func (x *ControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame.ProtoReflect.Descriptor instead.
func (*ControlFrame) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlFrame) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ControlFrame) GetMessage() isControlFrame_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControlFrame) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Message.(*ControlFrame_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *ControlFrame) GetServerHello() *ServerHello {
	if x != nil {
		if x, ok := x.Message.(*ControlFrame_ServerHello); ok {
			return x.ServerHello
		}
	}
	return nil
}

func (x *ControlFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*ControlFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ControlFrame) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Message.(*ControlFrame_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ControlFrame) GetClientGoodbye() *ClientGoodbye {
	if x != nil {
		if x, ok := x.Message.(*ControlFrame_ClientGoodbye); ok {
			return x.ClientGoodbye
		}
	}
	return nil
}

func (x *ControlFrame) GetGoAway() *GoAway {
	if x != nil {
		if x, ok := x.Message.(*ControlFrame_GoAway); ok {
			return x.GoAway
		}
	}
	return nil
}

type isControlFrame_Message interface {
	isControlFrame_Message()
}

type ControlFrame_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,10,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type ControlFrame_ServerHello struct {
	ServerHello *ServerHello `protobuf:"bytes,11,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type ControlFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type ControlFrame_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,13,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ControlFrame_ClientGoodbye struct {
	ClientGoodbye *ClientGoodbye `protobuf:"bytes,14,opt,name=client_goodbye,json=clientGoodbye,proto3,oneof"`
}

type ControlFrame_GoAway struct {
	GoAway *GoAway `protobuf:"bytes,15,opt,name=go_away,json=goAway,proto3,oneof"`
}

func (*ControlFrame_ClientHello) isControlFrame_Message() {}

func (*ControlFrame_ServerHello) isControlFrame_Message() {}

func (*ControlFrame_Heartbeat) isControlFrame_Message() {}

func (*ControlFrame_HeartbeatAck) isControlFrame_Message() {}

func (*ControlFrame_ClientGoodbye) isControlFrame_Message() {}

func (*ControlFrame_GoAway) isControlFrame_Message() {}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	StartupId     string                 `protobuf:"bytes,4,opt,name=startup_id,json=startupId,proto3" json:"startup_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_api_agent_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ClientHello) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClientHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *ClientHello) GetStartupId() string {
	if x != nil {
		return x.StartupId
	}
	return ""
}

func (x *ClientHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServerHello struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId            string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ServerTimeUnixMilli     int64                  `protobuf:"varint,2,opt,name=server_time_unix_milli,json=serverTimeUnixMilli,proto3" json:"server_time_unix_milli,omitempty"`
	HeartbeatIntervalMillis uint64                 `protobuf:"varint,3,opt,name=heartbeat_interval_millis,json=heartbeatIntervalMillis,proto3" json:"heartbeat_interval_millis,omitempty"`
	HeartbeatTimeoutMillis  uint64                 `protobuf:"varint,4,opt,name=heartbeat_timeout_millis,json=heartbeatTimeoutMillis,proto3" json:"heartbeat_timeout_millis,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_api_agent_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ServerHello) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ServerHello) GetServerTimeUnixMilli() int64 {
	if x != nil {
		return x.ServerTimeUnixMilli
	}
	return 0
}

func (x *ServerHello) GetHeartbeatIntervalMillis() uint64 {
	if x != nil {
		return x.HeartbeatIntervalMillis
	}
	return 0
}

func (x *ServerHello) GetHeartbeatTimeoutMillis() uint64 {
	if x != nil {
		return x.HeartbeatTimeoutMillis
	}
	return 0
}

type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sequence        uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentAtUnixMilli int64                  `protobuf:"varint,2,opt,name=sent_at_unix_milli,json=sentAtUnixMilli,proto3" json:"sent_at_unix_milli,omitempty"`
	Health          HealthStatus           `protobuf:"varint,3,opt,name=health,proto3,enum=zke.agent.v1.HealthStatus" json:"health,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_agent_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetSentAtUnixMilli() int64 {
	if x != nil {
		return x.SentAtUnixMilli
	}
	return 0
}

func (x *Heartbeat) GetHealth() HealthStatus {
	if x != nil {
		return x.Health
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

type HeartbeatAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Sequence            uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ServerTimeUnixMilli int64                  `protobuf:"varint,2,opt,name=server_time_unix_milli,json=serverTimeUnixMilli,proto3" json:"server_time_unix_milli,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_api_agent_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatAck) GetServerTimeUnixMilli() int64 {
	if x != nil {
		return x.ServerTimeUnixMilli
	}
	return 0
}

type ClientGoodbye struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGoodbye) Reset() {
	*x = ClientGoodbye{}
	mi := &file_api_agent_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGoodbye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGoodbye) ProtoMessage() {}

func (x *ClientGoodbye) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGoodbye.ProtoReflect.Descriptor instead.
func (*ClientGoodbye) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ClientGoodbye) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GoAway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoAway) Reset() {
	*x = GoAway{}
	mi := &file_api_agent_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoAway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoAway) ProtoMessage() {}

func (x *GoAway) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoAway.ProtoReflect.Descriptor instead.
func (*GoAway) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *GoAway) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_agent_v1_control_proto protoreflect.FileDescriptor

const file_api_agent_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/agent/v1/control.proto\x12\fzke.agent.v1\"\xb7\x03\n" +
	"\fControlFrame\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12>\n" +
	"\fclient_hello\x18\n" +
	" \x01(\v2\x19.zke.agent.v1.ClientHelloH\x00R\vclientHello\x12>\n" +
	"\fserver_hello\x18\v \x01(\v2\x19.zke.agent.v1.ServerHelloH\x00R\vserverHello\x127\n" +
	"\theartbeat\x18\f \x01(\v2\x17.zke.agent.v1.HeartbeatH\x00R\theartbeat\x12A\n" +
	"\rheartbeat_ack\x18\r \x01(\v2\x1a.zke.agent.v1.HeartbeatAckH\x00R\fheartbeatAck\x12D\n" +
	"\x0eclient_goodbye\x18\x0e \x01(\v2\x1b.zke.agent.v1.ClientGoodbyeH\x00R\rclientGoodbye\x12/\n" +
	"\ago_away\x18\x0f \x01(\v2\x14.zke.agent.v1.GoAwayH\x00R\x06goAwayB\t\n" +
	"\amessage\"\xaf\x01\n" +
	"\vClientHello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"startup_id\x18\x04 \x01(\tR\tstartupId\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\xdd\x01\n" +
	"\vServerHello\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x123\n" +
	"\x16server_time_unix_milli\x18\x02 \x01(\x03R\x13serverTimeUnixMilli\x12:\n" +
	"\x19heartbeat_interval_millis\x18\x03 \x01(\x04R\x17heartbeatIntervalMillis\x128\n" +
	"\x18heartbeat_timeout_millis\x18\x04 \x01(\x04R\x16heartbeatTimeoutMillis\"\x88\x01\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12+\n" +
	"\x12sent_at_unix_milli\x18\x02 \x01(\x03R\x0fsentAtUnixMilli\x122\n" +
	"\x06health\x18\x03 \x01(\x0e2\x1a.zke.agent.v1.HealthStatusR\x06health\"_\n" +
	"\fHeartbeatAck\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x123\n" +
	"\x16server_time_unix_milli\x18\x02 \x01(\x03R\x13serverTimeUnixMilli\"'\n" +
	"\rClientGoodbye\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\" \n" +
	"\x06GoAway\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*d\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_control_proto_rawDescOnce sync.Once
	file_api_agent_v1_control_proto_rawDescData []byte
)

func file_api_agent_v1_control_proto_rawDescGZIP() []byte {
	file_api_agent_v1_control_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_control_proto_rawDesc), len(file_api_agent_v1_control_proto_rawDesc)))
	})
	return file_api_agent_v1_control_proto_rawDescData
}

var file_api_agent_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_agent_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_agent_v1_control_proto_goTypes = []any{
	(HealthStatus)(0),     // 0: zke.agent.v1.HealthStatus
	(*ControlFrame)(nil),  // 1: zke.agent.v1.ControlFrame
	(*ClientHello)(nil),   // 2: zke.agent.v1.ClientHello
	(*ServerHello)(nil),   // 3: zke.agent.v1.ServerHello
	(*Heartbeat)(nil),     // 4: zke.agent.v1.Heartbeat
	(*HeartbeatAck)(nil),  // 5: zke.agent.v1.HeartbeatAck
	(*ClientGoodbye)(nil), // 6: zke.agent.v1.ClientGoodbye
	(*GoAway)(nil),        // 7: zke.agent.v1.GoAway
}
var file_api_agent_v1_control_proto_depIdxs = []int32{
	2, // 0: zke.agent.v1.ControlFrame.client_hello:type_name -> zke.agent.v1.ClientHello
	3, // 1: zke.agent.v1.ControlFrame.server_hello:type_name -> zke.agent.v1.ServerHello
	4, // 2: zke.agent.v1.ControlFrame.heartbeat:type_name -> zke.agent.v1.Heartbeat
	5, // 3: zke.agent.v1.ControlFrame.heartbeat_ack:type_name -> zke.agent.v1.HeartbeatAck
	6, // 4: zke.agent.v1.ControlFrame.client_goodbye:type_name -> zke.agent.v1.ClientGoodbye
	7, // 5: zke.agent.v1.ControlFrame.go_away:type_name -> zke.agent.v1.GoAway
	0, // 6: zke.agent.v1.Heartbeat.health:type_name -> zke.agent.v1.HealthStatus
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_agent_v1_control_proto_init() }
func file_api_agent_v1_control_proto_init() {
	if File_api_agent_v1_control_proto != nil {
		return
	}
	file_api_agent_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlFrame_ClientHello)(nil),
		(*ControlFrame_ServerHello)(nil),
		(*ControlFrame_Heartbeat)(nil),
		(*ControlFrame_HeartbeatAck)(nil),
		(*ControlFrame_ClientGoodbye)(nil),
		(*ControlFrame_GoAway)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_control_proto_rawDesc), len(file_api_agent_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_control_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_control_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_control_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_control_proto_msgTypes,
	}.Build()
	File_api_agent_v1_control_proto = out.File
	file_api_agent_v1_control_proto_goTypes = nil
	file_api_agent_v1_control_proto_depIdxs = nil
}
