// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/exec.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodExecOutputStream int32

const (
	PodExecOutputStream_POD_EXEC_OUTPUT_STREAM_UNSPECIFIED PodExecOutputStream = 0
	PodExecOutputStream_POD_EXEC_OUTPUT_STREAM_STDOUT      PodExecOutputStream = 1
	PodExecOutputStream_POD_EXEC_OUTPUT_STREAM_STDERR      PodExecOutputStream = 2
)

// Enum value maps for PodExecOutputStream.
var (
	PodExecOutputStream_name = map[int32]string{
		0: "POD_EXEC_OUTPUT_STREAM_UNSPECIFIED",
		1: "POD_EXEC_OUTPUT_STREAM_STDOUT",
		2: "POD_EXEC_OUTPUT_STREAM_STDERR",
	}
	PodExecOutputStream_value = map[string]int32{
		"POD_EXEC_OUTPUT_STREAM_UNSPECIFIED": 0,
		"POD_EXEC_OUTPUT_STREAM_STDOUT":      1,
		"POD_EXEC_OUTPUT_STREAM_STDERR":      2,
	}
)

func (x PodExecOutputStream) Enum() *PodExecOutputStream {
	p := new(PodExecOutputStream)
	*p = x
	return p
}

func (x PodExecOutputStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PodExecOutputStream) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_exec_proto_enumTypes[0].Descriptor()
}

func (PodExecOutputStream) Type() protoreflect.EnumType {
	return &file_api_agent_v1_exec_proto_enumTypes[0]
}

func (x PodExecOutputStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PodExecOutputStream.Descriptor instead.
func (PodExecOutputStream) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{0}
}

type PodExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName        string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid         string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Container      string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	Tty            bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	Columns        uint32                 `protobuf:"varint,6,opt,name=columns,proto3" json:"columns,omitempty"`
	Rows           uint32                 `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	MaxOutputBytes uint64                 `protobuf:"varint,8,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	MaxInputBytes  uint64                 `protobuf:"varint,9,opt,name=max_input_bytes,json=maxInputBytes,proto3" json:"max_input_bytes,omitempty"`
	// Empty keeps the interactive shell behavior used by Web Terminal. A
	// non-empty argv is only accepted for a ZKE-managed credential-proxy
	// Cluster Terminal Pod and runs without a TTY; this is the bounded command
	// path used by AIOps.
	Command       []string `protobuf:"bytes,10,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodExecRequest) Reset() {
	*x = PodExecRequest{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecRequest) ProtoMessage() {}

func (x *PodExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecRequest.ProtoReflect.Descriptor instead.
func (*PodExecRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{0}
}

func (x *PodExecRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodExecRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodExecRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodExecRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *PodExecRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *PodExecRequest) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *PodExecRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PodExecRequest) GetMaxOutputBytes() uint64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *PodExecRequest) GetMaxInputBytes() uint64 {
	if x != nil {
		return x.MaxInputBytes
	}
	return 0
}

func (x *PodExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type PodExecResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	PodUid               string                 `protobuf:"bytes,5,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Container            string                 `protobuf:"bytes,6,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PodExecResponse) Reset() {
	*x = PodExecResponse{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecResponse) ProtoMessage() {}

func (x *PodExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecResponse.ProtoReflect.Descriptor instead.
func (*PodExecResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{1}
}

func (x *PodExecResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *PodExecResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *PodExecResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PodExecResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodExecResponse) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodExecResponse) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type PodExecInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodExecInput) Reset() {
	*x = PodExecInput{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecInput) ProtoMessage() {}

func (x *PodExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecInput.ProtoReflect.Descriptor instead.
func (*PodExecInput) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{2}
}

func (x *PodExecInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PodExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       uint32                 `protobuf:"varint,1,opt,name=columns,proto3" json:"columns,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodExecResize) Reset() {
	*x = PodExecResize{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecResize) ProtoMessage() {}

func (x *PodExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecResize.ProtoReflect.Descriptor instead.
func (*PodExecResize) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{3}
}

func (x *PodExecResize) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *PodExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PodExecCloseInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodExecCloseInput) Reset() {
	*x = PodExecCloseInput{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecCloseInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecCloseInput) ProtoMessage() {}

func (x *PodExecCloseInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecCloseInput.ProtoReflect.Descriptor instead.
func (*PodExecCloseInput) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{4}
}

type PodExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        PodExecOutputStream    `protobuf:"varint,1,opt,name=stream,proto3,enum=zke.agent.v1.PodExecOutputStream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodExecOutput) Reset() {
	*x = PodExecOutput{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecOutput) ProtoMessage() {}

func (x *PodExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecOutput.ProtoReflect.Descriptor instead.
func (*PodExecOutput) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{5}
}

func (x *PodExecOutput) GetStream() PodExecOutputStream {
	if x != nil {
		return x.Stream
	}
	return PodExecOutputStream_POD_EXEC_OUTPUT_STREAM_UNSPECIFIED
}

func (x *PodExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PodExecExit struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Result             ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	ExitCode           int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	OutputBytes        uint64                 `protobuf:"varint,5,opt,name=output_bytes,json=outputBytes,proto3" json:"output_bytes,omitempty"`
	OutputLimitReached bool                   `protobuf:"varint,6,opt,name=output_limit_reached,json=outputLimitReached,proto3" json:"output_limit_reached,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PodExecExit) Reset() {
	*x = PodExecExit{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecExit) ProtoMessage() {}

func (x *PodExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecExit.ProtoReflect.Descriptor instead.
func (*PodExecExit) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{6}
}

func (x *PodExecExit) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *PodExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *PodExecExit) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PodExecExit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodExecExit) GetOutputBytes() uint64 {
	if x != nil {
		return x.OutputBytes
	}
	return 0
}

func (x *PodExecExit) GetOutputLimitReached() bool {
	if x != nil {
		return x.OutputLimitReached
	}
	return false
}

type PodExecFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PodExecFrame_Input
	//	*PodExecFrame_Resize
	//	*PodExecFrame_CloseInput
	//	*PodExecFrame_Output
	//	*PodExecFrame_Exit
	Message       isPodExecFrame_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodExecFrame) Reset() {
	*x = PodExecFrame{}
	mi := &file_api_agent_v1_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodExecFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodExecFrame) ProtoMessage() {}

func (x *PodExecFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodExecFrame.ProtoReflect.Descriptor instead.
func (*PodExecFrame) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_exec_proto_rawDescGZIP(), []int{7}
}

func (x *PodExecFrame) GetMessage() isPodExecFrame_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PodExecFrame) GetInput() *PodExecInput {
	if x != nil {
		if x, ok := x.Message.(*PodExecFrame_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *PodExecFrame) GetResize() *PodExecResize {
	if x != nil {
		if x, ok := x.Message.(*PodExecFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *PodExecFrame) GetCloseInput() *PodExecCloseInput {
	if x != nil {
		if x, ok := x.Message.(*PodExecFrame_CloseInput); ok {
			return x.CloseInput
		}
	}
	return nil
}

func (x *PodExecFrame) GetOutput() *PodExecOutput {
	if x != nil {
		if x, ok := x.Message.(*PodExecFrame_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *PodExecFrame) GetExit() *PodExecExit {
	if x != nil {
		if x, ok := x.Message.(*PodExecFrame_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isPodExecFrame_Message interface {
	isPodExecFrame_Message()
}

type PodExecFrame_Input struct {
	Input *PodExecInput `protobuf:"bytes,1,opt,name=input,proto3,oneof"`
}

type PodExecFrame_Resize struct {
	Resize *PodExecResize `protobuf:"bytes,2,opt,name=resize,proto3,oneof"`
}

type PodExecFrame_CloseInput struct {
	CloseInput *PodExecCloseInput `protobuf:"bytes,3,opt,name=close_input,json=closeInput,proto3,oneof"`
}

type PodExecFrame_Output struct {
	Output *PodExecOutput `protobuf:"bytes,4,opt,name=output,proto3,oneof"`
}

type PodExecFrame_Exit struct {
	Exit *PodExecExit `protobuf:"bytes,5,opt,name=exit,proto3,oneof"`
}

func (*PodExecFrame_Input) isPodExecFrame_Message() {}

func (*PodExecFrame_Resize) isPodExecFrame_Message() {}

func (*PodExecFrame_CloseInput) isPodExecFrame_Message() {}

func (*PodExecFrame_Output) isPodExecFrame_Message() {}

func (*PodExecFrame_Exit) isPodExecFrame_Message() {}

var File_api_agent_v1_exec_proto protoreflect.FileDescriptor

const file_api_agent_v1_exec_proto_rawDesc = "" +
	"\n" +
	"\x17api/agent/v1/exec.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"\xac\x02\n" +
	"\x0ePodExecRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x12\x18\n" +
	"\acolumns\x18\x06 \x01(\rR\acolumns\x12\x12\n" +
	"\x04rows\x18\a \x01(\rR\x04rows\x12(\n" +
	"\x10max_output_bytes\x18\b \x01(\x04R\x0emaxOutputBytes\x12&\n" +
	"\x0fmax_input_bytes\x18\t \x01(\x04R\rmaxInputBytes\x12\x18\n" +
	"\acommand\x18\n" +
	" \x03(\tR\acommand\"\xe2\x01\n" +
	"\x0fPodExecResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x17\n" +
	"\apod_uid\x18\x05 \x01(\tR\x06podUid\x12\x1c\n" +
	"\tcontainer\x18\x06 \x01(\tR\tcontainer\"\"\n" +
	"\fPodExecInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"=\n" +
	"\rPodExecResize\x12\x18\n" +
	"\acolumns\x18\x01 \x01(\rR\acolumns\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x13\n" +
	"\x11PodExecCloseInput\"^\n" +
	"\rPodExecOutput\x129\n" +
	"\x06stream\x18\x01 \x01(\x0e2!.zke.agent.v1.PodExecOutputStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xe3\x01\n" +
	"\vPodExecExit\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\foutput_bytes\x18\x05 \x01(\x04R\voutputBytes\x120\n" +
	"\x14output_limit_reached\x18\x06 \x01(\bR\x12outputLimitReached\"\xb0\x02\n" +
	"\fPodExecFrame\x122\n" +
	"\x05input\x18\x01 \x01(\v2\x1a.zke.agent.v1.PodExecInputH\x00R\x05input\x125\n" +
	"\x06resize\x18\x02 \x01(\v2\x1b.zke.agent.v1.PodExecResizeH\x00R\x06resize\x12B\n" +
	"\vclose_input\x18\x03 \x01(\v2\x1f.zke.agent.v1.PodExecCloseInputH\x00R\n" +
	"closeInput\x125\n" +
	"\x06output\x18\x04 \x01(\v2\x1b.zke.agent.v1.PodExecOutputH\x00R\x06output\x12/\n" +
	"\x04exit\x18\x05 \x01(\v2\x19.zke.agent.v1.PodExecExitH\x00R\x04exitB\t\n" +
	"\amessage*\x83\x01\n" +
	"\x13PodExecOutputStream\x12&\n" +
	"\"POD_EXEC_OUTPUT_STREAM_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPOD_EXEC_OUTPUT_STREAM_STDOUT\x10\x01\x12!\n" +
	"\x1dPOD_EXEC_OUTPUT_STREAM_STDERR\x10\x02B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_exec_proto_rawDescOnce sync.Once
	file_api_agent_v1_exec_proto_rawDescData []byte
)

func file_api_agent_v1_exec_proto_rawDescGZIP() []byte {
	file_api_agent_v1_exec_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_exec_proto_rawDesc), len(file_api_agent_v1_exec_proto_rawDesc)))
	})
	return file_api_agent_v1_exec_proto_rawDescData
}

var file_api_agent_v1_exec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_agent_v1_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_agent_v1_exec_proto_goTypes = []any{
	(PodExecOutputStream)(0),  // 0: zke.agent.v1.PodExecOutputStream
	(*PodExecRequest)(nil),    // 1: zke.agent.v1.PodExecRequest
	(*PodExecResponse)(nil),   // 2: zke.agent.v1.PodExecResponse
	(*PodExecInput)(nil),      // 3: zke.agent.v1.PodExecInput
	(*PodExecResize)(nil),     // 4: zke.agent.v1.PodExecResize
	(*PodExecCloseInput)(nil), // 5: zke.agent.v1.PodExecCloseInput
	(*PodExecOutput)(nil),     // 6: zke.agent.v1.PodExecOutput
	(*PodExecExit)(nil),       // 7: zke.agent.v1.PodExecExit
	(*PodExecFrame)(nil),      // 8: zke.agent.v1.PodExecFrame
	(ResultCode)(0),           // 9: zke.agent.v1.ResultCode
}
var file_api_agent_v1_exec_proto_depIdxs = []int32{
	9, // 0: zke.agent.v1.PodExecResponse.result:type_name -> zke.agent.v1.ResultCode
	0, // 1: zke.agent.v1.PodExecOutput.stream:type_name -> zke.agent.v1.PodExecOutputStream
	9, // 2: zke.agent.v1.PodExecExit.result:type_name -> zke.agent.v1.ResultCode
	3, // 3: zke.agent.v1.PodExecFrame.input:type_name -> zke.agent.v1.PodExecInput
	4, // 4: zke.agent.v1.PodExecFrame.resize:type_name -> zke.agent.v1.PodExecResize
	5, // 5: zke.agent.v1.PodExecFrame.close_input:type_name -> zke.agent.v1.PodExecCloseInput
	6, // 6: zke.agent.v1.PodExecFrame.output:type_name -> zke.agent.v1.PodExecOutput
	7, // 7: zke.agent.v1.PodExecFrame.exit:type_name -> zke.agent.v1.PodExecExit
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_agent_v1_exec_proto_init() }
func file_api_agent_v1_exec_proto_init() {
	if File_api_agent_v1_exec_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	file_api_agent_v1_exec_proto_msgTypes[7].OneofWrappers = []any{
		(*PodExecFrame_Input)(nil),
		(*PodExecFrame_Resize)(nil),
		(*PodExecFrame_CloseInput)(nil),
		(*PodExecFrame_Output)(nil),
		(*PodExecFrame_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_exec_proto_rawDesc), len(file_api_agent_v1_exec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_exec_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_exec_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_exec_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_exec_proto_msgTypes,
	}.Build()
	File_api_agent_v1_exec_proto = out.File
	file_api_agent_v1_exec_proto_goTypes = nil
	file_api_agent_v1_exec_proto_depIdxs = nil
}
