// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/helm.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Helm release lifecycle, executed inside the target Cluster.
//
// The Server never renders a chart and never writes a release Secret. Doing
// either correctly means running Helm's own engine — the template pipeline, the
// hook ordering, the history rewrite — and a Server that wrote release storage
// itself would corrupt the history the real `helm` client depends on. So the
// Server decides *what* should happen and sends the chart; the Agent, which is
// the side that has a Kubernetes connection at all, runs Helm.
//
// Everything that identifies the operation is in the message. The two variable
// length inputs — the values document and the chart archive — follow it on the
// Stream in that order, because a chart is far larger than one protocol frame.
type HelmAction int32

const (
	HelmAction_HELM_ACTION_UNSPECIFIED HelmAction = 0
	HelmAction_HELM_ACTION_INSTALL     HelmAction = 1
	HelmAction_HELM_ACTION_UPGRADE     HelmAction = 2
	HelmAction_HELM_ACTION_ROLLBACK    HelmAction = 3
	HelmAction_HELM_ACTION_UNINSTALL   HelmAction = 4
)

// Enum value maps for HelmAction.
var (
	HelmAction_name = map[int32]string{
		0: "HELM_ACTION_UNSPECIFIED",
		1: "HELM_ACTION_INSTALL",
		2: "HELM_ACTION_UPGRADE",
		3: "HELM_ACTION_ROLLBACK",
		4: "HELM_ACTION_UNINSTALL",
	}
	HelmAction_value = map[string]int32{
		"HELM_ACTION_UNSPECIFIED": 0,
		"HELM_ACTION_INSTALL":     1,
		"HELM_ACTION_UPGRADE":     2,
		"HELM_ACTION_ROLLBACK":    3,
		"HELM_ACTION_UNINSTALL":   4,
	}
)

func (x HelmAction) Enum() *HelmAction {
	p := new(HelmAction)
	*p = x
	return p
}

func (x HelmAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelmAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_helm_proto_enumTypes[0].Descriptor()
}

func (HelmAction) Type() protoreflect.EnumType {
	return &file_api_agent_v1_helm_proto_enumTypes[0]
}

func (x HelmAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelmAction.Descriptor instead.
func (HelmAction) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_helm_proto_rawDescGZIP(), []int{0}
}

type HelmRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Action      HelmAction             `protobuf:"varint,1,opt,name=action,proto3,enum=zke.agent.v1.HelmAction" json:"action,omitempty"`
	Namespace   string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName string                 `protobuf:"bytes,3,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
	// Bytes of the values document, sent first on the Stream. YAML, and may be
	// empty, which means "the chart's own defaults".
	ValuesSize uint64 `protobuf:"varint,4,opt,name=values_size,json=valuesSize,proto3" json:"values_size,omitempty"`
	// Bytes of the chart archive (.tgz), sent after the values. Set for INSTALL
	// and UPGRADE and zero for the two actions that operate on stored history.
	ChartSize uint64 `protobuf:"varint,5,opt,name=chart_size,json=chartSize,proto3" json:"chart_size,omitempty"`
	// A dry run renders and reports without writing anything: no objects, no
	// release Secret, no history. It is how a change is previewed before it is
	// made, so it is accepted for every action rather than for installs alone.
	DryRun bool `protobuf:"varint,6,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Create the target Namespace if it does not exist. Install only; an upgrade
	// whose Namespace has gone is a failure to report rather than to repair.
	CreateNamespace bool `protobuf:"varint,7,opt,name=create_namespace,json=createNamespace,proto3" json:"create_namespace,omitempty"`
	// Wait for the objects the release owns to become ready before reporting
	// success, bounded by timeout_seconds.
	Wait           bool   `protobuf:"varint,8,opt,name=wait,proto3" json:"wait,omitempty"`
	TimeoutSeconds uint32 `protobuf:"varint,9,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Roll the release back to where it was if the operation fails. It implies
	// waiting, and the Agent enables the wait rather than refusing the pair.
	Atomic bool `protobuf:"varint,10,opt,name=atomic,proto3" json:"atomic,omitempty"`
	// Skip the chart's hooks. Recorded and reported, because a release installed
	// without its hooks is not the release the chart describes.
	DisableHooks bool `protobuf:"varint,11,opt,name=disable_hooks,json=disableHooks,proto3" json:"disable_hooks,omitempty"`
	// Upgrade only, and mutually exclusive. Neither set means the values sent
	// with this request replace the previous ones exactly.
	ResetValues bool `protobuf:"varint,12,opt,name=reset_values,json=resetValues,proto3" json:"reset_values,omitempty"`
	ReuseValues bool `protobuf:"varint,13,opt,name=reuse_values,json=reuseValues,proto3" json:"reuse_values,omitempty"`
	// Rollback only: the revision to return to. Zero means the one before the
	// current release, which is what `helm rollback` does with no argument.
	Revision int64 `protobuf:"varint,14,opt,name=revision,proto3" json:"revision,omitempty"`
	// Uninstall only: keep the release history instead of deleting it with the
	// objects. A kept history is what a later rollback needs.
	KeepHistory bool `protobuf:"varint,15,opt,name=keep_history,json=keepHistory,proto3" json:"keep_history,omitempty"`
	// How many revisions Helm retains for this release. Zero leaves Helm's own
	// default in place.
	MaxHistory uint32 `protobuf:"varint,16,opt,name=max_history,json=maxHistory,proto3" json:"max_history,omitempty"`
	// Free text recorded on the revision, shown by `helm history`. The Server
	// fills it with who asked for the change.
	Description string `protobuf:"bytes,17,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the chart may create objects that are not confined to a Namespace
	// — a CustomResourceDefinition, a ClusterRole, a StorageClass. The Server
	// sets it only for an operator authorized over the Cluster as a whole,
	// because a Namespace grant says nothing about an object with no Namespace.
	// An Agent that predates this field ignores it and applies whatever the
	// chart renders, which is why the Server also refuses to send the request to
	// an Agent that does not advertise the Helm capability at all.
	AllowClusterScoped bool `protobuf:"varint,18,opt,name=allow_cluster_scoped,json=allowClusterScoped,proto3" json:"allow_cluster_scoped,omitempty"`
	// Report what Helm is doing while it is still doing it.
	//
	// A release change is the longest operation this protocol carries — a chart
	// that waits for a rollout holds the Stream open for minutes — and until the
	// response arrives the operator has nothing to read. When this is set the
	// Agent writes HelmEvent frames instead of a bare HelmResponse, so the
	// account of the operation arrives as it happens rather than after it.
	//
	// It changes the wire shape of the answer, so the Server sets it only for an
	// Agent that advertised `helm-progress.v1`. An Agent that predates the field
	// ignores it, never advertises the capability, and is never asked.
	StreamProgress bool `protobuf:"varint,19,opt,name=stream_progress,json=streamProgress,proto3" json:"stream_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelmRequest) Reset() {
	*x = HelmRequest{}
	mi := &file_api_agent_v1_helm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmRequest) ProtoMessage() {}

func (x *HelmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_helm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmRequest.ProtoReflect.Descriptor instead.
func (*HelmRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_helm_proto_rawDescGZIP(), []int{0}
}

func (x *HelmRequest) GetAction() HelmAction {
	if x != nil {
		return x.Action
	}
	return HelmAction_HELM_ACTION_UNSPECIFIED
}

func (x *HelmRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HelmRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *HelmRequest) GetValuesSize() uint64 {
	if x != nil {
		return x.ValuesSize
	}
	return 0
}

func (x *HelmRequest) GetChartSize() uint64 {
	if x != nil {
		return x.ChartSize
	}
	return 0
}

func (x *HelmRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *HelmRequest) GetCreateNamespace() bool {
	if x != nil {
		return x.CreateNamespace
	}
	return false
}

func (x *HelmRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

func (x *HelmRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HelmRequest) GetAtomic() bool {
	if x != nil {
		return x.Atomic
	}
	return false
}

func (x *HelmRequest) GetDisableHooks() bool {
	if x != nil {
		return x.DisableHooks
	}
	return false
}

func (x *HelmRequest) GetResetValues() bool {
	if x != nil {
		return x.ResetValues
	}
	return false
}

func (x *HelmRequest) GetReuseValues() bool {
	if x != nil {
		return x.ReuseValues
	}
	return false
}

func (x *HelmRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *HelmRequest) GetKeepHistory() bool {
	if x != nil {
		return x.KeepHistory
	}
	return false
}

func (x *HelmRequest) GetMaxHistory() uint32 {
	if x != nil {
		return x.MaxHistory
	}
	return 0
}

func (x *HelmRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HelmRequest) GetAllowClusterScoped() bool {
	if x != nil {
		return x.AllowClusterScoped
	}
	return false
}

func (x *HelmRequest) GetStreamProgress() bool {
	if x != nil {
		return x.StreamProgress
	}
	return false
}

// HelmProgress is one line of an operation that has not finished yet.
//
// The text is Helm's own log line, forwarded verbatim rather than classified.
// Helm says "creating 6 resource(s)" and "beginning wait for 6 resources with
// timeout of 5m0s"; an Agent that translated those into a phase enum would be
// guessing at a vocabulary Helm never promised, and the guess would be wrong on
// the release where it mattered. The Agent adds its own lines for what it does
// itself — loading the archive, and the outcome — and those read the same way.
//
// Progress is advisory. It is written on a best effort basis and dropped when
// it cannot be, because a Stream that failed to report what it was doing must
// still report what it did.
type HelmProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtUnixMillis  int64                  `protobuf:"varint,1,opt,name=at_unix_millis,json=atUnixMillis,proto3" json:"at_unix_millis,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmProgress) Reset() {
	*x = HelmProgress{}
	mi := &file_api_agent_v1_helm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmProgress) ProtoMessage() {}

func (x *HelmProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_helm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmProgress.ProtoReflect.Descriptor instead.
func (*HelmProgress) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_helm_proto_rawDescGZIP(), []int{1}
}

func (x *HelmProgress) GetAtUnixMillis() int64 {
	if x != nil {
		return x.AtUnixMillis
	}
	return 0
}

func (x *HelmProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HelmEvent is what a Stream carries back when the request asked for progress.
//
// Zero or more progress frames, then exactly one response, then the report body
// the response sizes. The oneof is what lets the Server tell "still running"
// from "finished" without a framing layer of its own.
type HelmEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HelmEvent_Progress
	//	*HelmEvent_Response
	Payload       isHelmEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmEvent) Reset() {
	*x = HelmEvent{}
	mi := &file_api_agent_v1_helm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmEvent) ProtoMessage() {}

func (x *HelmEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_helm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmEvent.ProtoReflect.Descriptor instead.
func (*HelmEvent) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_helm_proto_rawDescGZIP(), []int{2}
}

func (x *HelmEvent) GetPayload() isHelmEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HelmEvent) GetProgress() *HelmProgress {
	if x != nil {
		if x, ok := x.Payload.(*HelmEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *HelmEvent) GetResponse() *HelmResponse {
	if x != nil {
		if x, ok := x.Payload.(*HelmEvent_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isHelmEvent_Payload interface {
	isHelmEvent_Payload()
}

type HelmEvent_Progress struct {
	Progress *HelmProgress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type HelmEvent_Response struct {
	Response *HelmResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*HelmEvent_Progress) isHelmEvent_Payload() {}

func (*HelmEvent_Response) isHelmEvent_Payload() {}

type HelmResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Bytes of the JSON release report that follows the message. Present on
	// success, including a dry run, whose report carries the rendered manifest
	// and nothing else changed. Zero for a successful uninstall that kept no
	// history, which leaves no revision to report.
	BodySize      uint64 `protobuf:"varint,5,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmResponse) Reset() {
	*x = HelmResponse{}
	mi := &file_api_agent_v1_helm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmResponse) ProtoMessage() {}

func (x *HelmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_helm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmResponse.ProtoReflect.Descriptor instead.
func (*HelmResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_helm_proto_rawDescGZIP(), []int{3}
}

func (x *HelmResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *HelmResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *HelmResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HelmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelmResponse) GetBodySize() uint64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

var File_api_agent_v1_helm_proto protoreflect.FileDescriptor

const file_api_agent_v1_helm_proto_rawDesc = "" +
	"\n" +
	"\x17api/agent/v1/helm.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"\xa1\x05\n" +
	"\vHelmRequest\x120\n" +
	"\x06action\x18\x01 \x01(\x0e2\x18.zke.agent.v1.HelmActionR\x06action\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\frelease_name\x18\x03 \x01(\tR\vreleaseName\x12\x1f\n" +
	"\vvalues_size\x18\x04 \x01(\x04R\n" +
	"valuesSize\x12\x1d\n" +
	"\n" +
	"chart_size\x18\x05 \x01(\x04R\tchartSize\x12\x17\n" +
	"\adry_run\x18\x06 \x01(\bR\x06dryRun\x12)\n" +
	"\x10create_namespace\x18\a \x01(\bR\x0fcreateNamespace\x12\x12\n" +
	"\x04wait\x18\b \x01(\bR\x04wait\x12'\n" +
	"\x0ftimeout_seconds\x18\t \x01(\rR\x0etimeoutSeconds\x12\x16\n" +
	"\x06atomic\x18\n" +
	" \x01(\bR\x06atomic\x12#\n" +
	"\rdisable_hooks\x18\v \x01(\bR\fdisableHooks\x12!\n" +
	"\freset_values\x18\f \x01(\bR\vresetValues\x12!\n" +
	"\freuse_values\x18\r \x01(\bR\vreuseValues\x12\x1a\n" +
	"\brevision\x18\x0e \x01(\x03R\brevision\x12!\n" +
	"\fkeep_history\x18\x0f \x01(\bR\vkeepHistory\x12\x1f\n" +
	"\vmax_history\x18\x10 \x01(\rR\n" +
	"maxHistory\x12 \n" +
	"\vdescription\x18\x11 \x01(\tR\vdescription\x120\n" +
	"\x14allow_cluster_scoped\x18\x12 \x01(\bR\x12allowClusterScoped\x12'\n" +
	"\x0fstream_progress\x18\x13 \x01(\bR\x0estreamProgress\"N\n" +
	"\fHelmProgress\x12$\n" +
	"\x0eat_unix_millis\x18\x01 \x01(\x03R\fatUnixMillis\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8a\x01\n" +
	"\tHelmEvent\x128\n" +
	"\bprogress\x18\x01 \x01(\v2\x1a.zke.agent.v1.HelmProgressH\x00R\bprogress\x128\n" +
	"\bresponse\x18\x02 \x01(\v2\x1a.zke.agent.v1.HelmResponseH\x00R\bresponseB\t\n" +
	"\apayload\"\xc5\x01\n" +
	"\fHelmResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\tbody_size\x18\x05 \x01(\x04R\bbodySize*\x90\x01\n" +
	"\n" +
	"HelmAction\x12\x1b\n" +
	"\x17HELM_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HELM_ACTION_INSTALL\x10\x01\x12\x17\n" +
	"\x13HELM_ACTION_UPGRADE\x10\x02\x12\x18\n" +
	"\x14HELM_ACTION_ROLLBACK\x10\x03\x12\x19\n" +
	"\x15HELM_ACTION_UNINSTALL\x10\x04B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_helm_proto_rawDescOnce sync.Once
	file_api_agent_v1_helm_proto_rawDescData []byte
)

func file_api_agent_v1_helm_proto_rawDescGZIP() []byte {
	file_api_agent_v1_helm_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_helm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_helm_proto_rawDesc), len(file_api_agent_v1_helm_proto_rawDesc)))
	})
	return file_api_agent_v1_helm_proto_rawDescData
}

var file_api_agent_v1_helm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_agent_v1_helm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_agent_v1_helm_proto_goTypes = []any{
	(HelmAction)(0),      // 0: zke.agent.v1.HelmAction
	(*HelmRequest)(nil),  // 1: zke.agent.v1.HelmRequest
	(*HelmProgress)(nil), // 2: zke.agent.v1.HelmProgress
	(*HelmEvent)(nil),    // 3: zke.agent.v1.HelmEvent
	(*HelmResponse)(nil), // 4: zke.agent.v1.HelmResponse
	(ResultCode)(0),      // 5: zke.agent.v1.ResultCode
}
var file_api_agent_v1_helm_proto_depIdxs = []int32{
	0, // 0: zke.agent.v1.HelmRequest.action:type_name -> zke.agent.v1.HelmAction
	2, // 1: zke.agent.v1.HelmEvent.progress:type_name -> zke.agent.v1.HelmProgress
	4, // 2: zke.agent.v1.HelmEvent.response:type_name -> zke.agent.v1.HelmResponse
	5, // 3: zke.agent.v1.HelmResponse.result:type_name -> zke.agent.v1.ResultCode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_agent_v1_helm_proto_init() }
func file_api_agent_v1_helm_proto_init() {
	if File_api_agent_v1_helm_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	file_api_agent_v1_helm_proto_msgTypes[2].OneofWrappers = []any{
		(*HelmEvent_Progress)(nil),
		(*HelmEvent_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_helm_proto_rawDesc), len(file_api_agent_v1_helm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_helm_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_helm_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_helm_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_helm_proto_msgTypes,
	}.Build()
	File_api_agent_v1_helm_proto = out.File
	file_api_agent_v1_helm_proto_goTypes = nil
	file_api_agent_v1_helm_proto_depIdxs = nil
}
