// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/logs.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid        string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Container     string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	Previous      bool                   `protobuf:"varint,6,opt,name=previous,proto3" json:"previous,omitempty"`
	TailLines     *int64                 `protobuf:"varint,7,opt,name=tail_lines,json=tailLines,proto3,oneof" json:"tail_lines,omitempty"`
	SinceSeconds  *int64                 `protobuf:"varint,8,opt,name=since_seconds,json=sinceSeconds,proto3,oneof" json:"since_seconds,omitempty"`
	Timestamps    bool                   `protobuf:"varint,9,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	MaxBytes      uint64                 `protobuf:"varint,10,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodLogsRequest) Reset() {
	*x = PodLogsRequest{}
	mi := &file_api_agent_v1_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogsRequest) ProtoMessage() {}

func (x *PodLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogsRequest.ProtoReflect.Descriptor instead.
func (*PodLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_logs_proto_rawDescGZIP(), []int{0}
}

func (x *PodLogsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodLogsRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodLogsRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodLogsRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *PodLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *PodLogsRequest) GetPrevious() bool {
	if x != nil {
		return x.Previous
	}
	return false
}

func (x *PodLogsRequest) GetTailLines() int64 {
	if x != nil && x.TailLines != nil {
		return *x.TailLines
	}
	return 0
}

func (x *PodLogsRequest) GetSinceSeconds() int64 {
	if x != nil && x.SinceSeconds != nil {
		return *x.SinceSeconds
	}
	return 0
}

func (x *PodLogsRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

func (x *PodLogsRequest) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type PodLogsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	PodUid               string                 `protobuf:"bytes,5,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Container            string                 `protobuf:"bytes,6,opt,name=container,proto3" json:"container,omitempty"`
	Follow               bool                   `protobuf:"varint,7,opt,name=follow,proto3" json:"follow,omitempty"`
	ContentType          string                 `protobuf:"bytes,8,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PodLogsResponse) Reset() {
	*x = PodLogsResponse{}
	mi := &file_api_agent_v1_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogsResponse) ProtoMessage() {}

func (x *PodLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogsResponse.ProtoReflect.Descriptor instead.
func (*PodLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_logs_proto_rawDescGZIP(), []int{1}
}

func (x *PodLogsResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *PodLogsResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *PodLogsResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PodLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodLogsResponse) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodLogsResponse) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *PodLogsResponse) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *PodLogsResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type PodLogsChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodLogsChunk) Reset() {
	*x = PodLogsChunk{}
	mi := &file_api_agent_v1_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogsChunk) ProtoMessage() {}

func (x *PodLogsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogsChunk.ProtoReflect.Descriptor instead.
func (*PodLogsChunk) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_logs_proto_rawDescGZIP(), []int{2}
}

func (x *PodLogsChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PodLogsTrailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	LimitReached  bool                   `protobuf:"varint,5,opt,name=limit_reached,json=limitReached,proto3" json:"limit_reached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodLogsTrailer) Reset() {
	*x = PodLogsTrailer{}
	mi := &file_api_agent_v1_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogsTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogsTrailer) ProtoMessage() {}

func (x *PodLogsTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogsTrailer.ProtoReflect.Descriptor instead.
func (*PodLogsTrailer) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_logs_proto_rawDescGZIP(), []int{3}
}

func (x *PodLogsTrailer) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *PodLogsTrailer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PodLogsTrailer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodLogsTrailer) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *PodLogsTrailer) GetLimitReached() bool {
	if x != nil {
		return x.LimitReached
	}
	return false
}

type PodLogsFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PodLogsFrame_Chunk
	//	*PodLogsFrame_Trailer
	Message       isPodLogsFrame_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodLogsFrame) Reset() {
	*x = PodLogsFrame{}
	mi := &file_api_agent_v1_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogsFrame) ProtoMessage() {}

func (x *PodLogsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogsFrame.ProtoReflect.Descriptor instead.
func (*PodLogsFrame) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_logs_proto_rawDescGZIP(), []int{4}
}

func (x *PodLogsFrame) GetMessage() isPodLogsFrame_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PodLogsFrame) GetChunk() *PodLogsChunk {
	if x != nil {
		if x, ok := x.Message.(*PodLogsFrame_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *PodLogsFrame) GetTrailer() *PodLogsTrailer {
	if x != nil {
		if x, ok := x.Message.(*PodLogsFrame_Trailer); ok {
			return x.Trailer
		}
	}
	return nil
}

type isPodLogsFrame_Message interface {
	isPodLogsFrame_Message()
}

type PodLogsFrame_Chunk struct {
	Chunk *PodLogsChunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type PodLogsFrame_Trailer struct {
	Trailer *PodLogsTrailer `protobuf:"bytes,2,opt,name=trailer,proto3,oneof"`
}

func (*PodLogsFrame_Chunk) isPodLogsFrame_Message() {}

func (*PodLogsFrame_Trailer) isPodLogsFrame_Message() {}

var File_api_agent_v1_logs_proto protoreflect.FileDescriptor

const file_api_agent_v1_logs_proto_rawDesc = "" +
	"\n" +
	"\x17api/agent/v1/logs.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"\xe0\x02\n" +
	"\x0ePodLogsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\x12\x1a\n" +
	"\bprevious\x18\x06 \x01(\bR\bprevious\x12\"\n" +
	"\n" +
	"tail_lines\x18\a \x01(\x03H\x00R\ttailLines\x88\x01\x01\x12(\n" +
	"\rsince_seconds\x18\b \x01(\x03H\x01R\fsinceSeconds\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"timestamps\x18\t \x01(\bR\n" +
	"timestamps\x12\x1b\n" +
	"\tmax_bytes\x18\n" +
	" \x01(\x04R\bmaxBytesB\r\n" +
	"\v_tail_linesB\x10\n" +
	"\x0e_since_seconds\"\x9d\x02\n" +
	"\x0fPodLogsResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x17\n" +
	"\apod_uid\x18\x05 \x01(\tR\x06podUid\x12\x1c\n" +
	"\tcontainer\x18\x06 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06follow\x18\a \x01(\bR\x06follow\x12!\n" +
	"\fcontent_type\x18\b \x01(\tR\vcontentType\"\"\n" +
	"\fPodLogsChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xb8\x01\n" +
	"\x0ePodLogsTrailer\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12#\n" +
	"\rlimit_reached\x18\x05 \x01(\bR\flimitReached\"\x87\x01\n" +
	"\fPodLogsFrame\x122\n" +
	"\x05chunk\x18\x01 \x01(\v2\x1a.zke.agent.v1.PodLogsChunkH\x00R\x05chunk\x128\n" +
	"\atrailer\x18\x02 \x01(\v2\x1c.zke.agent.v1.PodLogsTrailerH\x00R\atrailerB\t\n" +
	"\amessageB0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_logs_proto_rawDescOnce sync.Once
	file_api_agent_v1_logs_proto_rawDescData []byte
)

func file_api_agent_v1_logs_proto_rawDescGZIP() []byte {
	file_api_agent_v1_logs_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_logs_proto_rawDesc), len(file_api_agent_v1_logs_proto_rawDesc)))
	})
	return file_api_agent_v1_logs_proto_rawDescData
}

var file_api_agent_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_agent_v1_logs_proto_goTypes = []any{
	(*PodLogsRequest)(nil),  // 0: zke.agent.v1.PodLogsRequest
	(*PodLogsResponse)(nil), // 1: zke.agent.v1.PodLogsResponse
	(*PodLogsChunk)(nil),    // 2: zke.agent.v1.PodLogsChunk
	(*PodLogsTrailer)(nil),  // 3: zke.agent.v1.PodLogsTrailer
	(*PodLogsFrame)(nil),    // 4: zke.agent.v1.PodLogsFrame
	(ResultCode)(0),         // 5: zke.agent.v1.ResultCode
}
var file_api_agent_v1_logs_proto_depIdxs = []int32{
	5, // 0: zke.agent.v1.PodLogsResponse.result:type_name -> zke.agent.v1.ResultCode
	5, // 1: zke.agent.v1.PodLogsTrailer.result:type_name -> zke.agent.v1.ResultCode
	2, // 2: zke.agent.v1.PodLogsFrame.chunk:type_name -> zke.agent.v1.PodLogsChunk
	3, // 3: zke.agent.v1.PodLogsFrame.trailer:type_name -> zke.agent.v1.PodLogsTrailer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_agent_v1_logs_proto_init() }
func file_api_agent_v1_logs_proto_init() {
	if File_api_agent_v1_logs_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	file_api_agent_v1_logs_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_agent_v1_logs_proto_msgTypes[4].OneofWrappers = []any{
		(*PodLogsFrame_Chunk)(nil),
		(*PodLogsFrame_Trailer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_logs_proto_rawDesc), len(file_api_agent_v1_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_logs_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_logs_proto_depIdxs,
		MessageInfos:      file_api_agent_v1_logs_proto_msgTypes,
	}.Build()
	File_api_agent_v1_logs_proto = out.File
	file_api_agent_v1_logs_proto_goTypes = nil
	file_api_agent_v1_logs_proto_depIdxs = nil
}
