// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/metrics.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metrics Ingest is the first Agent-initiated business Stream: the Agent is
// the sender, forwarding payloads its in-cluster collector produced. Every
// other business Stream is opened by the Server, so this one must not reuse
// their Stream kinds or their handler paths.
type MetricsPayloadEncoding int32

const (
	MetricsPayloadEncoding_METRICS_PAYLOAD_ENCODING_UNSPECIFIED MetricsPayloadEncoding = 0
	// Snappy-compressed Prometheus remote write request body, forwarded byte
	// for byte. The Agent never parses or rewrites it; scope identity is
	// applied by the Server, which is the only side that cannot be modified by
	// whoever administers the target Cluster.
	MetricsPayloadEncoding_METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY MetricsPayloadEncoding = 1
)

// Enum value maps for MetricsPayloadEncoding.
var (
	MetricsPayloadEncoding_name = map[int32]string{
		0: "METRICS_PAYLOAD_ENCODING_UNSPECIFIED",
		1: "METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY",
	}
	MetricsPayloadEncoding_value = map[string]int32{
		"METRICS_PAYLOAD_ENCODING_UNSPECIFIED":                    0,
		"METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY": 1,
	}
)

func (x MetricsPayloadEncoding) Enum() *MetricsPayloadEncoding {
	p := new(MetricsPayloadEncoding)
	*p = x
	return p
}

func (x MetricsPayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsPayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricsPayloadEncoding) Type() protoreflect.EnumType {
	return &file_api_agent_v1_metrics_proto_enumTypes[0]
}

func (x MetricsPayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsPayloadEncoding.Descriptor instead.
func (MetricsPayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{0}
}

type MetricsCollectorAction int32

const (
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_UNSPECIFIED MetricsCollectorAction = 0
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_STATUS      MetricsCollectorAction = 1
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_INSTALL     MetricsCollectorAction = 2
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_UNINSTALL   MetricsCollectorAction = 3
	// DETAILS is separate from STATUS because discovering annotated Services
	// and Endpoints lists cluster-wide objects. The Console only asks for it
	// after somebody opens one Cluster's detail page; the fleet list keeps its
	// lightweight status poll.
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_DETAILS MetricsCollectorAction = 4
)

// Enum value maps for MetricsCollectorAction.
var (
	MetricsCollectorAction_name = map[int32]string{
		0: "METRICS_COLLECTOR_ACTION_UNSPECIFIED",
		1: "METRICS_COLLECTOR_ACTION_STATUS",
		2: "METRICS_COLLECTOR_ACTION_INSTALL",
		3: "METRICS_COLLECTOR_ACTION_UNINSTALL",
		4: "METRICS_COLLECTOR_ACTION_DETAILS",
	}
	MetricsCollectorAction_value = map[string]int32{
		"METRICS_COLLECTOR_ACTION_UNSPECIFIED": 0,
		"METRICS_COLLECTOR_ACTION_STATUS":      1,
		"METRICS_COLLECTOR_ACTION_INSTALL":     2,
		"METRICS_COLLECTOR_ACTION_UNINSTALL":   3,
		"METRICS_COLLECTOR_ACTION_DETAILS":     4,
	}
)

func (x MetricsCollectorAction) Enum() *MetricsCollectorAction {
	p := new(MetricsCollectorAction)
	*p = x
	return p
}

func (x MetricsCollectorAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsCollectorAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_metrics_proto_enumTypes[1].Descriptor()
}

func (MetricsCollectorAction) Type() protoreflect.EnumType {
	return &file_api_agent_v1_metrics_proto_enumTypes[1]
}

func (x MetricsCollectorAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsCollectorAction.Descriptor instead.
func (MetricsCollectorAction) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{1}
}

type MetricsIngestHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Collector       string                 `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	PayloadEncoding MetricsPayloadEncoding `protobuf:"varint,2,opt,name=payload_encoding,json=payloadEncoding,proto3,enum=zke.agent.v1.MetricsPayloadEncoding" json:"payload_encoding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricsIngestHello) Reset() {
	*x = MetricsIngestHello{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestHello) ProtoMessage() {}

func (x *MetricsIngestHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestHello.ProtoReflect.Descriptor instead.
func (*MetricsIngestHello) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsIngestHello) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

func (x *MetricsIngestHello) GetPayloadEncoding() MetricsPayloadEncoding {
	if x != nil {
		return x.PayloadEncoding
	}
	return MetricsPayloadEncoding_METRICS_PAYLOAD_ENCODING_UNSPECIFIED
}

type MetricsIngestReady struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Result  ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	Reason  string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Server-side limits. The Agent must apply the smaller of these and its own
	// configuration, so that neither side can be pushed past its budget by the
	// other.
	MaxBatchBytes      uint64 `protobuf:"varint,4,opt,name=max_batch_bytes,json=maxBatchBytes,proto3" json:"max_batch_bytes,omitempty"`
	MaxInFlightBatches uint32 `protobuf:"varint,5,opt,name=max_in_flight_batches,json=maxInFlightBatches,proto3" json:"max_in_flight_batches,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricsIngestReady) Reset() {
	*x = MetricsIngestReady{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestReady) ProtoMessage() {}

func (x *MetricsIngestReady) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestReady.ProtoReflect.Descriptor instead.
func (*MetricsIngestReady) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsIngestReady) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *MetricsIngestReady) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MetricsIngestReady) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetricsIngestReady) GetMaxBatchBytes() uint64 {
	if x != nil {
		return x.MaxBatchBytes
	}
	return 0
}

func (x *MetricsIngestReady) GetMaxInFlightBatches() uint32 {
	if x != nil {
		return x.MaxInFlightBatches
	}
	return 0
}

type MetricsIngestBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PayloadSize   uint64                 `protobuf:"varint,2,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsIngestBatch) Reset() {
	*x = MetricsIngestBatch{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestBatch) ProtoMessage() {}

func (x *MetricsIngestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestBatch.ProtoReflect.Descriptor instead.
func (*MetricsIngestBatch) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsIngestBatch) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *MetricsIngestBatch) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

// The collector is installed by the Agent inside its own Cluster rather than by
// the Server writing objects through the generic resource path. Two reasons:
// the object set is fixed, so the Agent can refuse anything that does not match
// it, and the ingest credential never has to leave the Cluster — the Agent both
// issues it and verifies it.
type MetricsCollectorRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Action             MetricsCollectorAction `protobuf:"varint,1,opt,name=action,proto3,enum=zke.agent.v1.MetricsCollectorAction" json:"action,omitempty"`
	Image              string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullPolicy    string                 `protobuf:"bytes,3,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	ScrapeInterval     string                 `protobuf:"bytes,4,opt,name=scrape_interval,json=scrapeInterval,proto3" json:"scrape_interval,omitempty"`
	BufferSize         string                 `protobuf:"bytes,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	KubeletMetricsPort uint32                 `protobuf:"varint,6,opt,name=kubelet_metrics_port,json=kubeletMetricsPort,proto3" json:"kubelet_metrics_port,omitempty"`
	// Kubernetes quantities for the collector container, decided by the Server
	// from platform settings so a Cluster cannot be handed an unbounded
	// workload by omission. Each may be empty, which drops that entry from the
	// container instead of sending Kubernetes a value it would reject; an empty
	// limit means the collector is only bounded by the Namespace's own limits.
	// An Agent too old to know these fields ignores them and installs as before.
	CpuRequest    string `protobuf:"bytes,7,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	MemoryRequest string `protobuf:"bytes,8,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	CpuLimit      string `protobuf:"bytes,9,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   string `protobuf:"bytes,10,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	// The two additional scrape targets. They carry the same shape as the
	// collector's own fields above, which stay flat so an Agent too old to know
	// these messages still installs the collector exactly as it used to — it
	// ignores what it cannot parse and renders a scrape configuration with the
	// kubelet target alone.
	//
	// An empty message means the Server does not want that target installed.
	KubeStateMetrics *MetricsCollectorComponent `protobuf:"bytes,11,opt,name=kube_state_metrics,json=kubeStateMetrics,proto3" json:"kube_state_metrics,omitempty"`
	NodeExporter     *MetricsCollectorComponent `protobuf:"bytes,12,opt,name=node_exporter,json=nodeExporter,proto3" json:"node_exporter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsCollectorRequest) Reset() {
	*x = MetricsCollectorRequest{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCollectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCollectorRequest) ProtoMessage() {}

func (x *MetricsCollectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCollectorRequest.ProtoReflect.Descriptor instead.
func (*MetricsCollectorRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsCollectorRequest) GetAction() MetricsCollectorAction {
	if x != nil {
		return x.Action
	}
	return MetricsCollectorAction_METRICS_COLLECTOR_ACTION_UNSPECIFIED
}

func (x *MetricsCollectorRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MetricsCollectorRequest) GetImagePullPolicy() string {
	if x != nil {
		return x.ImagePullPolicy
	}
	return ""
}

func (x *MetricsCollectorRequest) GetScrapeInterval() string {
	if x != nil {
		return x.ScrapeInterval
	}
	return ""
}

func (x *MetricsCollectorRequest) GetBufferSize() string {
	if x != nil {
		return x.BufferSize
	}
	return ""
}

func (x *MetricsCollectorRequest) GetKubeletMetricsPort() uint32 {
	if x != nil {
		return x.KubeletMetricsPort
	}
	return 0
}

func (x *MetricsCollectorRequest) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *MetricsCollectorRequest) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *MetricsCollectorRequest) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *MetricsCollectorRequest) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *MetricsCollectorRequest) GetKubeStateMetrics() *MetricsCollectorComponent {
	if x != nil {
		return x.KubeStateMetrics
	}
	return nil
}

func (x *MetricsCollectorRequest) GetNodeExporter() *MetricsCollectorComponent {
	if x != nil {
		return x.NodeExporter
	}
	return nil
}

// MetricsCollectorComponent is what the Server decides about one installed
// workload. The Agent still owns the object's shape; this only says which image
// runs it and how much of the Cluster it may take.
type MetricsCollectorComponent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Image           string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullPolicy string                 `protobuf:"bytes,2,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	CpuRequest      string                 `protobuf:"bytes,3,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	MemoryRequest   string                 `protobuf:"bytes,4,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	CpuLimit        string                 `protobuf:"bytes,5,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit     string                 `protobuf:"bytes,6,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricsCollectorComponent) Reset() {
	*x = MetricsCollectorComponent{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCollectorComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCollectorComponent) ProtoMessage() {}

func (x *MetricsCollectorComponent) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCollectorComponent.ProtoReflect.Descriptor instead.
func (*MetricsCollectorComponent) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsCollectorComponent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MetricsCollectorComponent) GetImagePullPolicy() string {
	if x != nil {
		return x.ImagePullPolicy
	}
	return ""
}

func (x *MetricsCollectorComponent) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *MetricsCollectorComponent) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *MetricsCollectorComponent) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *MetricsCollectorComponent) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type MetricsCollectorState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Installed       bool                   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Image           string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	DesiredReplicas int32                  `protobuf:"varint,4,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	ReadyReplicas   int32                  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// Whether the Agent holds a credential the collector can present. It is
	// reported as a fact, never as a value.
	CredentialReady bool `protobuf:"varint,6,opt,name=credential_ready,json=credentialReady,proto3" json:"credential_ready,omitempty"`
	// One entry per component the Agent knows about, including the collector
	// itself. The three fields above stay for the collector so an older Server
	// reading this response still sees what it expects.
	Components []*MetricsComponentState `protobuf:"bytes,7,rep,name=components,proto3" json:"components,omitempty"`
	// Present on a DETAILS response. STATUS deliberately leaves it empty.
	ScrapeJobs          []*MetricsScrapeJob `protobuf:"bytes,8,rep,name=scrape_jobs,json=scrapeJobs,proto3" json:"scrape_jobs,omitempty"`
	ScrapeJobsTruncated bool                `protobuf:"varint,9,opt,name=scrape_jobs_truncated,json=scrapeJobsTruncated,proto3" json:"scrape_jobs_truncated,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetricsCollectorState) Reset() {
	*x = MetricsCollectorState{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCollectorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCollectorState) ProtoMessage() {}

func (x *MetricsCollectorState) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCollectorState.ProtoReflect.Descriptor instead.
func (*MetricsCollectorState) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsCollectorState) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *MetricsCollectorState) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetricsCollectorState) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MetricsCollectorState) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *MetricsCollectorState) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *MetricsCollectorState) GetCredentialReady() bool {
	if x != nil {
		return x.CredentialReady
	}
	return false
}

func (x *MetricsCollectorState) GetComponents() []*MetricsComponentState {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *MetricsCollectorState) GetScrapeJobs() []*MetricsScrapeJob {
	if x != nil {
		return x.ScrapeJobs
	}
	return nil
}

func (x *MetricsCollectorState) GetScrapeJobsTruncated() bool {
	if x != nil {
		return x.ScrapeJobsTruncated
	}
	return false
}

// MetricsScrapeJob is one effective job shown in collector details. Built-in
// jobs have source_kind "Builtin" and no Kubernetes identity; annotated jobs
// name the Service or Endpoints object that opted its ready endpoints in.
type MetricsScrapeJob struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobName            string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	SourceKind         string                 `protobuf:"bytes,2,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	Namespace          string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SourceName         string                 `protobuf:"bytes,4,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Scheme             string                 `protobuf:"bytes,5,opt,name=scheme,proto3" json:"scheme,omitempty"`
	MetricsPath        string                 `protobuf:"bytes,6,opt,name=metrics_path,json=metricsPath,proto3" json:"metrics_path,omitempty"`
	Port               string                 `protobuf:"bytes,7,opt,name=port,proto3" json:"port,omitempty"`
	Authentication     string                 `protobuf:"bytes,8,opt,name=authentication,proto3" json:"authentication,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,9,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	Targets            []string               `protobuf:"bytes,10,rep,name=targets,proto3" json:"targets,omitempty"`
	TargetsTruncated   bool                   `protobuf:"varint,11,opt,name=targets_truncated,json=targetsTruncated,proto3" json:"targets_truncated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricsScrapeJob) Reset() {
	*x = MetricsScrapeJob{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsScrapeJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsScrapeJob) ProtoMessage() {}

func (x *MetricsScrapeJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsScrapeJob.ProtoReflect.Descriptor instead.
func (*MetricsScrapeJob) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsScrapeJob) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *MetricsScrapeJob) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *MetricsScrapeJob) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetricsScrapeJob) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *MetricsScrapeJob) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *MetricsScrapeJob) GetMetricsPath() string {
	if x != nil {
		return x.MetricsPath
	}
	return ""
}

func (x *MetricsScrapeJob) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *MetricsScrapeJob) GetAuthentication() string {
	if x != nil {
		return x.Authentication
	}
	return ""
}

func (x *MetricsScrapeJob) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *MetricsScrapeJob) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *MetricsScrapeJob) GetTargetsTruncated() bool {
	if x != nil {
		return x.TargetsTruncated
	}
	return false
}

type MetricsComponentState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component is one of the identifiers in pkg/shared/observability.
	Component       string `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	Installed       bool   `protobuf:"varint,2,opt,name=installed,proto3" json:"installed,omitempty"`
	Image           string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	DesiredReplicas int32  `protobuf:"varint,4,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	ReadyReplicas   int32  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// UnavailableReason is set when this component is not installed for a reason
	// the operator has to act on rather than because nobody asked for it. The
	// node metrics exporter needs host namespaces and host paths, which a
	// Namespace running under a restrictive Pod Security admission level refuses;
	// that refusal must be reported rather than retried forever, and it must not
	// fail the whole install — the rest of the pipeline works without it.
	UnavailableReason  string `protobuf:"bytes,6,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	UnavailableMessage string `protobuf:"bytes,7,opt,name=unavailable_message,json=unavailableMessage,proto3" json:"unavailable_message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricsComponentState) Reset() {
	*x = MetricsComponentState{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsComponentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsComponentState) ProtoMessage() {}

func (x *MetricsComponentState) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsComponentState.ProtoReflect.Descriptor instead.
func (*MetricsComponentState) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsComponentState) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MetricsComponentState) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *MetricsComponentState) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MetricsComponentState) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *MetricsComponentState) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *MetricsComponentState) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

func (x *MetricsComponentState) GetUnavailableMessage() string {
	if x != nil {
		return x.UnavailableMessage
	}
	return ""
}

type MetricsCollectorResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	State                *MetricsCollectorState `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MetricsCollectorResponse) Reset() {
	*x = MetricsCollectorResponse{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCollectorResponse) ProtoMessage() {}

func (x *MetricsCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCollectorResponse.ProtoReflect.Descriptor instead.
func (*MetricsCollectorResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsCollectorResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *MetricsCollectorResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *MetricsCollectorResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MetricsCollectorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetricsCollectorResponse) GetState() *MetricsCollectorState {
	if x != nil {
		return x.State
	}
	return nil
}

type MetricsIngestAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BatchId uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Result  ResultCode             `protobuf:"varint,2,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	Reason  string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Set with RESULT_CODE_RESOURCE_EXHAUSTED so the Agent can translate the
	// rejection into a retry hint for its in-cluster collector instead of
	// dropping the batch.
	RetryAfterMillis uint64 `protobuf:"varint,5,opt,name=retry_after_millis,json=retryAfterMillis,proto3" json:"retry_after_millis,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsIngestAck) Reset() {
	*x = MetricsIngestAck{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestAck) ProtoMessage() {}

func (x *MetricsIngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestAck.ProtoReflect.Descriptor instead.
func (*MetricsIngestAck) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsIngestAck) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *MetricsIngestAck) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *MetricsIngestAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MetricsIngestAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetricsIngestAck) GetRetryAfterMillis() uint64 {
	if x != nil {
		return x.RetryAfterMillis
	}
	return 0
}

var File_api_agent_v1_metrics_proto protoreflect.FileDescriptor

const file_api_agent_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/agent/v1/metrics.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"\x83\x01\n" +
	"\x12MetricsIngestHello\x12\x1c\n" +
	"\tcollector\x18\x01 \x01(\tR\tcollector\x12O\n" +
	"\x10payload_encoding\x18\x02 \x01(\x0e2$.zke.agent.v1.MetricsPayloadEncodingR\x0fpayloadEncoding\"\xd3\x01\n" +
	"\x12MetricsIngestReady\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0fmax_batch_bytes\x18\x04 \x01(\x04R\rmaxBatchBytes\x121\n" +
	"\x15max_in_flight_batches\x18\x05 \x01(\rR\x12maxInFlightBatches\"R\n" +
	"\x12MetricsIngestBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12!\n" +
	"\fpayload_size\x18\x02 \x01(\x04R\vpayloadSize\"\xc2\x04\n" +
	"\x17MetricsCollectorRequest\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.zke.agent.v1.MetricsCollectorActionR\x06action\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12*\n" +
	"\x11image_pull_policy\x18\x03 \x01(\tR\x0fimagePullPolicy\x12'\n" +
	"\x0fscrape_interval\x18\x04 \x01(\tR\x0escrapeInterval\x12\x1f\n" +
	"\vbuffer_size\x18\x05 \x01(\tR\n" +
	"bufferSize\x120\n" +
	"\x14kubelet_metrics_port\x18\x06 \x01(\rR\x12kubeletMetricsPort\x12\x1f\n" +
	"\vcpu_request\x18\a \x01(\tR\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\b \x01(\tR\rmemoryRequest\x12\x1b\n" +
	"\tcpu_limit\x18\t \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\n" +
	" \x01(\tR\vmemoryLimit\x12U\n" +
	"\x12kube_state_metrics\x18\v \x01(\v2'.zke.agent.v1.MetricsCollectorComponentR\x10kubeStateMetrics\x12L\n" +
	"\rnode_exporter\x18\f \x01(\v2'.zke.agent.v1.MetricsCollectorComponentR\fnodeExporter\"\xe5\x01\n" +
	"\x19MetricsCollectorComponent\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12*\n" +
	"\x11image_pull_policy\x18\x02 \x01(\tR\x0fimagePullPolicy\x12\x1f\n" +
	"\vcpu_request\x18\x03 \x01(\tR\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\x04 \x01(\tR\rmemoryRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x05 \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x06 \x01(\tR\vmemoryLimit\"\xa0\x03\n" +
	"\x15MetricsCollectorState\x12\x1c\n" +
	"\tinstalled\x18\x01 \x01(\bR\tinstalled\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12)\n" +
	"\x10desired_replicas\x18\x04 \x01(\x05R\x0fdesiredReplicas\x12%\n" +
	"\x0eready_replicas\x18\x05 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10credential_ready\x18\x06 \x01(\bR\x0fcredentialReady\x12C\n" +
	"\n" +
	"components\x18\a \x03(\v2#.zke.agent.v1.MetricsComponentStateR\n" +
	"components\x12?\n" +
	"\vscrape_jobs\x18\b \x03(\v2\x1e.zke.agent.v1.MetricsScrapeJobR\n" +
	"scrapeJobs\x122\n" +
	"\x15scrape_jobs_truncated\x18\t \x01(\bR\x13scrapeJobsTruncated\"\xfd\x02\n" +
	"\x10MetricsScrapeJob\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x1f\n" +
	"\vsource_kind\x18\x02 \x01(\tR\n" +
	"sourceKind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vsource_name\x18\x04 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06scheme\x18\x05 \x01(\tR\x06scheme\x12!\n" +
	"\fmetrics_path\x18\x06 \x01(\tR\vmetricsPath\x12\x12\n" +
	"\x04port\x18\a \x01(\tR\x04port\x12&\n" +
	"\x0eauthentication\x18\b \x01(\tR\x0eauthentication\x120\n" +
	"\x14insecure_skip_verify\x18\t \x01(\bR\x12insecureSkipVerify\x12\x18\n" +
	"\atargets\x18\n" +
	" \x03(\tR\atargets\x12+\n" +
	"\x11targets_truncated\x18\v \x01(\bR\x10targetsTruncated\"\x9b\x02\n" +
	"\x15MetricsComponentState\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x1c\n" +
	"\tinstalled\x18\x02 \x01(\bR\tinstalled\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12)\n" +
	"\x10desired_replicas\x18\x04 \x01(\x05R\x0fdesiredReplicas\x12%\n" +
	"\x0eready_replicas\x18\x05 \x01(\x05R\rreadyReplicas\x12-\n" +
	"\x12unavailable_reason\x18\x06 \x01(\tR\x11unavailableReason\x12/\n" +
	"\x13unavailable_message\x18\a \x01(\tR\x12unavailableMessage\"\xef\x01\n" +
	"\x18MetricsCollectorResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\x05state\x18\x05 \x01(\v2#.zke.agent.v1.MetricsCollectorStateR\x05state\"\xbf\x01\n" +
	"\x10MetricsIngestAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x120\n" +
	"\x06result\x18\x02 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12,\n" +
	"\x12retry_after_millis\x18\x05 \x01(\x04R\x10retryAfterMillis*\x7f\n" +
	"\x16MetricsPayloadEncoding\x12(\n" +
	"$METRICS_PAYLOAD_ENCODING_UNSPECIFIED\x10\x00\x12;\n" +
	"7METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY\x10\x01*\xdb\x01\n" +
	"\x16MetricsCollectorAction\x12(\n" +
	"$METRICS_COLLECTOR_ACTION_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fMETRICS_COLLECTOR_ACTION_STATUS\x10\x01\x12$\n" +
	" METRICS_COLLECTOR_ACTION_INSTALL\x10\x02\x12&\n" +
	"\"METRICS_COLLECTOR_ACTION_UNINSTALL\x10\x03\x12$\n" +
	" METRICS_COLLECTOR_ACTION_DETAILS\x10\x04B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_metrics_proto_rawDescOnce sync.Once
	file_api_agent_v1_metrics_proto_rawDescData []byte
)

func file_api_agent_v1_metrics_proto_rawDescGZIP() []byte {
	file_api_agent_v1_metrics_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_metrics_proto_rawDesc), len(file_api_agent_v1_metrics_proto_rawDesc)))
	})
	return file_api_agent_v1_metrics_proto_rawDescData
}

var file_api_agent_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_agent_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_agent_v1_metrics_proto_goTypes = []any{
	(MetricsPayloadEncoding)(0),       // 0: zke.agent.v1.MetricsPayloadEncoding
	(MetricsCollectorAction)(0),       // 1: zke.agent.v1.MetricsCollectorAction
	(*MetricsIngestHello)(nil),        // 2: zke.agent.v1.MetricsIngestHello
	(*MetricsIngestReady)(nil),        // 3: zke.agent.v1.MetricsIngestReady
	(*MetricsIngestBatch)(nil),        // 4: zke.agent.v1.MetricsIngestBatch
	(*MetricsCollectorRequest)(nil),   // 5: zke.agent.v1.MetricsCollectorRequest
	(*MetricsCollectorComponent)(nil), // 6: zke.agent.v1.MetricsCollectorComponent
	(*MetricsCollectorState)(nil),     // 7: zke.agent.v1.MetricsCollectorState
	(*MetricsScrapeJob)(nil),          // 8: zke.agent.v1.MetricsScrapeJob
	(*MetricsComponentState)(nil),     // 9: zke.agent.v1.MetricsComponentState
	(*MetricsCollectorResponse)(nil),  // 10: zke.agent.v1.MetricsCollectorResponse
	(*MetricsIngestAck)(nil),          // 11: zke.agent.v1.MetricsIngestAck
	(ResultCode)(0),                   // 12: zke.agent.v1.ResultCode
}
var file_api_agent_v1_metrics_proto_depIdxs = []int32{
	0,  // 0: zke.agent.v1.MetricsIngestHello.payload_encoding:type_name -> zke.agent.v1.MetricsPayloadEncoding
	12, // 1: zke.agent.v1.MetricsIngestReady.result:type_name -> zke.agent.v1.ResultCode
	1,  // 2: zke.agent.v1.MetricsCollectorRequest.action:type_name -> zke.agent.v1.MetricsCollectorAction
	6,  // 3: zke.agent.v1.MetricsCollectorRequest.kube_state_metrics:type_name -> zke.agent.v1.MetricsCollectorComponent
	6,  // 4: zke.agent.v1.MetricsCollectorRequest.node_exporter:type_name -> zke.agent.v1.MetricsCollectorComponent
	9,  // 5: zke.agent.v1.MetricsCollectorState.components:type_name -> zke.agent.v1.MetricsComponentState
	8,  // 6: zke.agent.v1.MetricsCollectorState.scrape_jobs:type_name -> zke.agent.v1.MetricsScrapeJob
	12, // 7: zke.agent.v1.MetricsCollectorResponse.result:type_name -> zke.agent.v1.ResultCode
	7,  // 8: zke.agent.v1.MetricsCollectorResponse.state:type_name -> zke.agent.v1.MetricsCollectorState
	12, // 9: zke.agent.v1.MetricsIngestAck.result:type_name -> zke.agent.v1.ResultCode
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_agent_v1_metrics_proto_init() }
func file_api_agent_v1_metrics_proto_init() {
	if File_api_agent_v1_metrics_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_metrics_proto_rawDesc), len(file_api_agent_v1_metrics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_metrics_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_metrics_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_metrics_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_metrics_proto_msgTypes,
	}.Build()
	File_api_agent_v1_metrics_proto = out.File
	file_api_agent_v1_metrics_proto_goTypes = nil
	file_api_agent_v1_metrics_proto_depIdxs = nil
}
