// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/metrics.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metrics Ingest is the first Agent-initiated business Stream: the Agent is
// the sender, forwarding payloads its in-cluster collector produced. Every
// other business Stream is opened by the Server, so this one must not reuse
// their Stream kinds or their handler paths.
type MetricsPayloadEncoding int32

const (
	MetricsPayloadEncoding_METRICS_PAYLOAD_ENCODING_UNSPECIFIED MetricsPayloadEncoding = 0
	// Snappy-compressed Prometheus remote write request body, forwarded byte
	// for byte. The Agent never parses or rewrites it; scope identity is
	// applied by the Server, which is the only side that cannot be modified by
	// whoever administers the target Cluster.
	MetricsPayloadEncoding_METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY MetricsPayloadEncoding = 1
)

// Enum value maps for MetricsPayloadEncoding.
var (
	MetricsPayloadEncoding_name = map[int32]string{
		0: "METRICS_PAYLOAD_ENCODING_UNSPECIFIED",
		1: "METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY",
	}
	MetricsPayloadEncoding_value = map[string]int32{
		"METRICS_PAYLOAD_ENCODING_UNSPECIFIED":                    0,
		"METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY": 1,
	}
)

func (x MetricsPayloadEncoding) Enum() *MetricsPayloadEncoding {
	p := new(MetricsPayloadEncoding)
	*p = x
	return p
}

func (x MetricsPayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsPayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricsPayloadEncoding) Type() protoreflect.EnumType {
	return &file_api_agent_v1_metrics_proto_enumTypes[0]
}

func (x MetricsPayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsPayloadEncoding.Descriptor instead.
func (MetricsPayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{0}
}

type MetricsCollectorAction int32

const (
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_UNSPECIFIED MetricsCollectorAction = 0
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_STATUS      MetricsCollectorAction = 1
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_INSTALL     MetricsCollectorAction = 2
	MetricsCollectorAction_METRICS_COLLECTOR_ACTION_UNINSTALL   MetricsCollectorAction = 3
)

// Enum value maps for MetricsCollectorAction.
var (
	MetricsCollectorAction_name = map[int32]string{
		0: "METRICS_COLLECTOR_ACTION_UNSPECIFIED",
		1: "METRICS_COLLECTOR_ACTION_STATUS",
		2: "METRICS_COLLECTOR_ACTION_INSTALL",
		3: "METRICS_COLLECTOR_ACTION_UNINSTALL",
	}
	MetricsCollectorAction_value = map[string]int32{
		"METRICS_COLLECTOR_ACTION_UNSPECIFIED": 0,
		"METRICS_COLLECTOR_ACTION_STATUS":      1,
		"METRICS_COLLECTOR_ACTION_INSTALL":     2,
		"METRICS_COLLECTOR_ACTION_UNINSTALL":   3,
	}
)

func (x MetricsCollectorAction) Enum() *MetricsCollectorAction {
	p := new(MetricsCollectorAction)
	*p = x
	return p
}

func (x MetricsCollectorAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsCollectorAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_metrics_proto_enumTypes[1].Descriptor()
}

func (MetricsCollectorAction) Type() protoreflect.EnumType {
	return &file_api_agent_v1_metrics_proto_enumTypes[1]
}

func (x MetricsCollectorAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsCollectorAction.Descriptor instead.
func (MetricsCollectorAction) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{1}
}

type MetricsIngestHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Collector       string                 `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	PayloadEncoding MetricsPayloadEncoding `protobuf:"varint,2,opt,name=payload_encoding,json=payloadEncoding,proto3,enum=zke.agent.v1.MetricsPayloadEncoding" json:"payload_encoding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricsIngestHello) Reset() {
	*x = MetricsIngestHello{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestHello) ProtoMessage() {}

func (x *MetricsIngestHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestHello.ProtoReflect.Descriptor instead.
func (*MetricsIngestHello) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsIngestHello) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

func (x *MetricsIngestHello) GetPayloadEncoding() MetricsPayloadEncoding {
	if x != nil {
		return x.PayloadEncoding
	}
	return MetricsPayloadEncoding_METRICS_PAYLOAD_ENCODING_UNSPECIFIED
}

type MetricsIngestReady struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Result  ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	Reason  string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Server-side limits. The Agent must apply the smaller of these and its own
	// configuration, so that neither side can be pushed past its budget by the
	// other.
	MaxBatchBytes      uint64 `protobuf:"varint,4,opt,name=max_batch_bytes,json=maxBatchBytes,proto3" json:"max_batch_bytes,omitempty"`
	MaxInFlightBatches uint32 `protobuf:"varint,5,opt,name=max_in_flight_batches,json=maxInFlightBatches,proto3" json:"max_in_flight_batches,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricsIngestReady) Reset() {
	*x = MetricsIngestReady{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestReady) ProtoMessage() {}

func (x *MetricsIngestReady) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestReady.ProtoReflect.Descriptor instead.
func (*MetricsIngestReady) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsIngestReady) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *MetricsIngestReady) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MetricsIngestReady) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetricsIngestReady) GetMaxBatchBytes() uint64 {
	if x != nil {
		return x.MaxBatchBytes
	}
	return 0
}

func (x *MetricsIngestReady) GetMaxInFlightBatches() uint32 {
	if x != nil {
		return x.MaxInFlightBatches
	}
	return 0
}

type MetricsIngestBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PayloadSize   uint64                 `protobuf:"varint,2,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsIngestBatch) Reset() {
	*x = MetricsIngestBatch{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestBatch) ProtoMessage() {}

func (x *MetricsIngestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestBatch.ProtoReflect.Descriptor instead.
func (*MetricsIngestBatch) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsIngestBatch) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *MetricsIngestBatch) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

// The collector is installed by the Agent inside its own Cluster rather than by
// the Server writing objects through the generic resource path. Two reasons:
// the object set is fixed, so the Agent can refuse anything that does not match
// it, and the ingest credential never has to leave the Cluster — the Agent both
// issues it and verifies it.
type MetricsCollectorRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Action             MetricsCollectorAction `protobuf:"varint,1,opt,name=action,proto3,enum=zke.agent.v1.MetricsCollectorAction" json:"action,omitempty"`
	Image              string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullPolicy    string                 `protobuf:"bytes,3,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	ScrapeInterval     string                 `protobuf:"bytes,4,opt,name=scrape_interval,json=scrapeInterval,proto3" json:"scrape_interval,omitempty"`
	BufferSize         string                 `protobuf:"bytes,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	KubeletMetricsPort uint32                 `protobuf:"varint,6,opt,name=kubelet_metrics_port,json=kubeletMetricsPort,proto3" json:"kubelet_metrics_port,omitempty"`
	// Kubernetes quantities for the collector container, decided by the Server
	// from platform settings so a Cluster cannot be handed an unbounded
	// workload by omission. Each may be empty, which drops that entry from the
	// container instead of sending Kubernetes a value it would reject; an empty
	// limit means the collector is only bounded by the Namespace's own limits.
	// An Agent too old to know these fields ignores them and installs as before.
	CpuRequest    string `protobuf:"bytes,7,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	MemoryRequest string `protobuf:"bytes,8,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	CpuLimit      string `protobuf:"bytes,9,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   string `protobuf:"bytes,10,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsCollectorRequest) Reset() {
	*x = MetricsCollectorRequest{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCollectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCollectorRequest) ProtoMessage() {}

func (x *MetricsCollectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCollectorRequest.ProtoReflect.Descriptor instead.
func (*MetricsCollectorRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsCollectorRequest) GetAction() MetricsCollectorAction {
	if x != nil {
		return x.Action
	}
	return MetricsCollectorAction_METRICS_COLLECTOR_ACTION_UNSPECIFIED
}

func (x *MetricsCollectorRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MetricsCollectorRequest) GetImagePullPolicy() string {
	if x != nil {
		return x.ImagePullPolicy
	}
	return ""
}

func (x *MetricsCollectorRequest) GetScrapeInterval() string {
	if x != nil {
		return x.ScrapeInterval
	}
	return ""
}

func (x *MetricsCollectorRequest) GetBufferSize() string {
	if x != nil {
		return x.BufferSize
	}
	return ""
}

func (x *MetricsCollectorRequest) GetKubeletMetricsPort() uint32 {
	if x != nil {
		return x.KubeletMetricsPort
	}
	return 0
}

func (x *MetricsCollectorRequest) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *MetricsCollectorRequest) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *MetricsCollectorRequest) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *MetricsCollectorRequest) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type MetricsCollectorState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Installed       bool                   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Image           string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	DesiredReplicas int32                  `protobuf:"varint,4,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	ReadyReplicas   int32                  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// Whether the Agent holds a credential the collector can present. It is
	// reported as a fact, never as a value.
	CredentialReady bool `protobuf:"varint,6,opt,name=credential_ready,json=credentialReady,proto3" json:"credential_ready,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricsCollectorState) Reset() {
	*x = MetricsCollectorState{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCollectorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCollectorState) ProtoMessage() {}

func (x *MetricsCollectorState) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCollectorState.ProtoReflect.Descriptor instead.
func (*MetricsCollectorState) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsCollectorState) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *MetricsCollectorState) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetricsCollectorState) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MetricsCollectorState) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *MetricsCollectorState) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *MetricsCollectorState) GetCredentialReady() bool {
	if x != nil {
		return x.CredentialReady
	}
	return false
}

type MetricsCollectorResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	State                *MetricsCollectorState `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MetricsCollectorResponse) Reset() {
	*x = MetricsCollectorResponse{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsCollectorResponse) ProtoMessage() {}

func (x *MetricsCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsCollectorResponse.ProtoReflect.Descriptor instead.
func (*MetricsCollectorResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsCollectorResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *MetricsCollectorResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *MetricsCollectorResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MetricsCollectorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetricsCollectorResponse) GetState() *MetricsCollectorState {
	if x != nil {
		return x.State
	}
	return nil
}

type MetricsIngestAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BatchId uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Result  ResultCode             `protobuf:"varint,2,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	Reason  string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Set with RESULT_CODE_RESOURCE_EXHAUSTED so the Agent can translate the
	// rejection into a retry hint for its in-cluster collector instead of
	// dropping the batch.
	RetryAfterMillis uint64 `protobuf:"varint,5,opt,name=retry_after_millis,json=retryAfterMillis,proto3" json:"retry_after_millis,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsIngestAck) Reset() {
	*x = MetricsIngestAck{}
	mi := &file_api_agent_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsIngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsIngestAck) ProtoMessage() {}

func (x *MetricsIngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsIngestAck.ProtoReflect.Descriptor instead.
func (*MetricsIngestAck) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsIngestAck) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *MetricsIngestAck) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *MetricsIngestAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MetricsIngestAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetricsIngestAck) GetRetryAfterMillis() uint64 {
	if x != nil {
		return x.RetryAfterMillis
	}
	return 0
}

var File_api_agent_v1_metrics_proto protoreflect.FileDescriptor

const file_api_agent_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/agent/v1/metrics.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"\x83\x01\n" +
	"\x12MetricsIngestHello\x12\x1c\n" +
	"\tcollector\x18\x01 \x01(\tR\tcollector\x12O\n" +
	"\x10payload_encoding\x18\x02 \x01(\x0e2$.zke.agent.v1.MetricsPayloadEncodingR\x0fpayloadEncoding\"\xd3\x01\n" +
	"\x12MetricsIngestReady\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0fmax_batch_bytes\x18\x04 \x01(\x04R\rmaxBatchBytes\x121\n" +
	"\x15max_in_flight_batches\x18\x05 \x01(\rR\x12maxInFlightBatches\"R\n" +
	"\x12MetricsIngestBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12!\n" +
	"\fpayload_size\x18\x02 \x01(\x04R\vpayloadSize\"\x9d\x03\n" +
	"\x17MetricsCollectorRequest\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.zke.agent.v1.MetricsCollectorActionR\x06action\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12*\n" +
	"\x11image_pull_policy\x18\x03 \x01(\tR\x0fimagePullPolicy\x12'\n" +
	"\x0fscrape_interval\x18\x04 \x01(\tR\x0escrapeInterval\x12\x1f\n" +
	"\vbuffer_size\x18\x05 \x01(\tR\n" +
	"bufferSize\x120\n" +
	"\x14kubelet_metrics_port\x18\x06 \x01(\rR\x12kubeletMetricsPort\x12\x1f\n" +
	"\vcpu_request\x18\a \x01(\tR\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\b \x01(\tR\rmemoryRequest\x12\x1b\n" +
	"\tcpu_limit\x18\t \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\n" +
	" \x01(\tR\vmemoryLimit\"\xe6\x01\n" +
	"\x15MetricsCollectorState\x12\x1c\n" +
	"\tinstalled\x18\x01 \x01(\bR\tinstalled\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12)\n" +
	"\x10desired_replicas\x18\x04 \x01(\x05R\x0fdesiredReplicas\x12%\n" +
	"\x0eready_replicas\x18\x05 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10credential_ready\x18\x06 \x01(\bR\x0fcredentialReady\"\xef\x01\n" +
	"\x18MetricsCollectorResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\x05state\x18\x05 \x01(\v2#.zke.agent.v1.MetricsCollectorStateR\x05state\"\xbf\x01\n" +
	"\x10MetricsIngestAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x120\n" +
	"\x06result\x18\x02 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12,\n" +
	"\x12retry_after_millis\x18\x05 \x01(\x04R\x10retryAfterMillis*\x7f\n" +
	"\x16MetricsPayloadEncoding\x12(\n" +
	"$METRICS_PAYLOAD_ENCODING_UNSPECIFIED\x10\x00\x12;\n" +
	"7METRICS_PAYLOAD_ENCODING_PROMETHEUS_REMOTE_WRITE_SNAPPY\x10\x01*\xb5\x01\n" +
	"\x16MetricsCollectorAction\x12(\n" +
	"$METRICS_COLLECTOR_ACTION_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fMETRICS_COLLECTOR_ACTION_STATUS\x10\x01\x12$\n" +
	" METRICS_COLLECTOR_ACTION_INSTALL\x10\x02\x12&\n" +
	"\"METRICS_COLLECTOR_ACTION_UNINSTALL\x10\x03B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_metrics_proto_rawDescOnce sync.Once
	file_api_agent_v1_metrics_proto_rawDescData []byte
)

func file_api_agent_v1_metrics_proto_rawDescGZIP() []byte {
	file_api_agent_v1_metrics_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_metrics_proto_rawDesc), len(file_api_agent_v1_metrics_proto_rawDesc)))
	})
	return file_api_agent_v1_metrics_proto_rawDescData
}

var file_api_agent_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_agent_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_agent_v1_metrics_proto_goTypes = []any{
	(MetricsPayloadEncoding)(0),      // 0: zke.agent.v1.MetricsPayloadEncoding
	(MetricsCollectorAction)(0),      // 1: zke.agent.v1.MetricsCollectorAction
	(*MetricsIngestHello)(nil),       // 2: zke.agent.v1.MetricsIngestHello
	(*MetricsIngestReady)(nil),       // 3: zke.agent.v1.MetricsIngestReady
	(*MetricsIngestBatch)(nil),       // 4: zke.agent.v1.MetricsIngestBatch
	(*MetricsCollectorRequest)(nil),  // 5: zke.agent.v1.MetricsCollectorRequest
	(*MetricsCollectorState)(nil),    // 6: zke.agent.v1.MetricsCollectorState
	(*MetricsCollectorResponse)(nil), // 7: zke.agent.v1.MetricsCollectorResponse
	(*MetricsIngestAck)(nil),         // 8: zke.agent.v1.MetricsIngestAck
	(ResultCode)(0),                  // 9: zke.agent.v1.ResultCode
}
var file_api_agent_v1_metrics_proto_depIdxs = []int32{
	0, // 0: zke.agent.v1.MetricsIngestHello.payload_encoding:type_name -> zke.agent.v1.MetricsPayloadEncoding
	9, // 1: zke.agent.v1.MetricsIngestReady.result:type_name -> zke.agent.v1.ResultCode
	1, // 2: zke.agent.v1.MetricsCollectorRequest.action:type_name -> zke.agent.v1.MetricsCollectorAction
	9, // 3: zke.agent.v1.MetricsCollectorResponse.result:type_name -> zke.agent.v1.ResultCode
	6, // 4: zke.agent.v1.MetricsCollectorResponse.state:type_name -> zke.agent.v1.MetricsCollectorState
	9, // 5: zke.agent.v1.MetricsIngestAck.result:type_name -> zke.agent.v1.ResultCode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_agent_v1_metrics_proto_init() }
func file_api_agent_v1_metrics_proto_init() {
	if File_api_agent_v1_metrics_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_metrics_proto_rawDesc), len(file_api_agent_v1_metrics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_metrics_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_metrics_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_metrics_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_metrics_proto_msgTypes,
	}.Build()
	File_api_agent_v1_metrics_proto = out.File
	file_api_agent_v1_metrics_proto_goTypes = nil
	file_api_agent_v1_metrics_proto_depIdxs = nil
}
