// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/portforward.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodPortForwardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName        string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid         string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Port           uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	MaxClientBytes uint64                 `protobuf:"varint,5,opt,name=max_client_bytes,json=maxClientBytes,proto3" json:"max_client_bytes,omitempty"`
	MaxPodBytes    uint64                 `protobuf:"varint,6,opt,name=max_pod_bytes,json=maxPodBytes,proto3" json:"max_pod_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PodPortForwardRequest) Reset() {
	*x = PodPortForwardRequest{}
	mi := &file_api_agent_v1_portforward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodPortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPortForwardRequest) ProtoMessage() {}

func (x *PodPortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_portforward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPortForwardRequest.ProtoReflect.Descriptor instead.
func (*PodPortForwardRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_portforward_proto_rawDescGZIP(), []int{0}
}

func (x *PodPortForwardRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodPortForwardRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodPortForwardRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodPortForwardRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PodPortForwardRequest) GetMaxClientBytes() uint64 {
	if x != nil {
		return x.MaxClientBytes
	}
	return 0
}

func (x *PodPortForwardRequest) GetMaxPodBytes() uint64 {
	if x != nil {
		return x.MaxPodBytes
	}
	return 0
}

type PodPortForwardResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	PodUid               string                 `protobuf:"bytes,5,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Port                 uint32                 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PodPortForwardResponse) Reset() {
	*x = PodPortForwardResponse{}
	mi := &file_api_agent_v1_portforward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodPortForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPortForwardResponse) ProtoMessage() {}

func (x *PodPortForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_portforward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPortForwardResponse.ProtoReflect.Descriptor instead.
func (*PodPortForwardResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_portforward_proto_rawDescGZIP(), []int{1}
}

func (x *PodPortForwardResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *PodPortForwardResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *PodPortForwardResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PodPortForwardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodPortForwardResponse) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodPortForwardResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PodPortForwardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodPortForwardData) Reset() {
	*x = PodPortForwardData{}
	mi := &file_api_agent_v1_portforward_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodPortForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPortForwardData) ProtoMessage() {}

func (x *PodPortForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_portforward_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPortForwardData.ProtoReflect.Descriptor instead.
func (*PodPortForwardData) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_portforward_proto_rawDescGZIP(), []int{2}
}

func (x *PodPortForwardData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PodPortForwardCloseInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodPortForwardCloseInput) Reset() {
	*x = PodPortForwardCloseInput{}
	mi := &file_api_agent_v1_portforward_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodPortForwardCloseInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPortForwardCloseInput) ProtoMessage() {}

func (x *PodPortForwardCloseInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_portforward_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPortForwardCloseInput.ProtoReflect.Descriptor instead.
func (*PodPortForwardCloseInput) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_portforward_proto_rawDescGZIP(), []int{3}
}

type PodPortForwardExit struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Result             ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	Reason             string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ClientBytes        uint64                 `protobuf:"varint,4,opt,name=client_bytes,json=clientBytes,proto3" json:"client_bytes,omitempty"`
	PodBytes           uint64                 `protobuf:"varint,5,opt,name=pod_bytes,json=podBytes,proto3" json:"pod_bytes,omitempty"`
	ClientLimitReached bool                   `protobuf:"varint,6,opt,name=client_limit_reached,json=clientLimitReached,proto3" json:"client_limit_reached,omitempty"`
	PodLimitReached    bool                   `protobuf:"varint,7,opt,name=pod_limit_reached,json=podLimitReached,proto3" json:"pod_limit_reached,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PodPortForwardExit) Reset() {
	*x = PodPortForwardExit{}
	mi := &file_api_agent_v1_portforward_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodPortForwardExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPortForwardExit) ProtoMessage() {}

func (x *PodPortForwardExit) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_portforward_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPortForwardExit.ProtoReflect.Descriptor instead.
func (*PodPortForwardExit) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_portforward_proto_rawDescGZIP(), []int{4}
}

func (x *PodPortForwardExit) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *PodPortForwardExit) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PodPortForwardExit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodPortForwardExit) GetClientBytes() uint64 {
	if x != nil {
		return x.ClientBytes
	}
	return 0
}

func (x *PodPortForwardExit) GetPodBytes() uint64 {
	if x != nil {
		return x.PodBytes
	}
	return 0
}

func (x *PodPortForwardExit) GetClientLimitReached() bool {
	if x != nil {
		return x.ClientLimitReached
	}
	return false
}

func (x *PodPortForwardExit) GetPodLimitReached() bool {
	if x != nil {
		return x.PodLimitReached
	}
	return false
}

type PodPortForwardFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PodPortForwardFrame_Data
	//	*PodPortForwardFrame_CloseInput
	//	*PodPortForwardFrame_Exit
	Message       isPodPortForwardFrame_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodPortForwardFrame) Reset() {
	*x = PodPortForwardFrame{}
	mi := &file_api_agent_v1_portforward_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodPortForwardFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPortForwardFrame) ProtoMessage() {}

func (x *PodPortForwardFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_portforward_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPortForwardFrame.ProtoReflect.Descriptor instead.
func (*PodPortForwardFrame) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_portforward_proto_rawDescGZIP(), []int{5}
}

func (x *PodPortForwardFrame) GetMessage() isPodPortForwardFrame_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PodPortForwardFrame) GetData() *PodPortForwardData {
	if x != nil {
		if x, ok := x.Message.(*PodPortForwardFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *PodPortForwardFrame) GetCloseInput() *PodPortForwardCloseInput {
	if x != nil {
		if x, ok := x.Message.(*PodPortForwardFrame_CloseInput); ok {
			return x.CloseInput
		}
	}
	return nil
}

func (x *PodPortForwardFrame) GetExit() *PodPortForwardExit {
	if x != nil {
		if x, ok := x.Message.(*PodPortForwardFrame_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isPodPortForwardFrame_Message interface {
	isPodPortForwardFrame_Message()
}

type PodPortForwardFrame_Data struct {
	Data *PodPortForwardData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type PodPortForwardFrame_CloseInput struct {
	CloseInput *PodPortForwardCloseInput `protobuf:"bytes,2,opt,name=close_input,json=closeInput,proto3,oneof"`
}

type PodPortForwardFrame_Exit struct {
	Exit *PodPortForwardExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*PodPortForwardFrame_Data) isPodPortForwardFrame_Message() {}

func (*PodPortForwardFrame_CloseInput) isPodPortForwardFrame_Message() {}

func (*PodPortForwardFrame_Exit) isPodPortForwardFrame_Message() {}

var File_api_agent_v1_portforward_proto protoreflect.FileDescriptor

const file_api_agent_v1_portforward_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/agent/v1/portforward.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"\xcb\x01\n" +
	"\x15PodPortForwardRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12(\n" +
	"\x10max_client_bytes\x18\x05 \x01(\x04R\x0emaxClientBytes\x12\"\n" +
	"\rmax_pod_bytes\x18\x06 \x01(\x04R\vmaxPodBytes\"\xdf\x01\n" +
	"\x16PodPortForwardResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x17\n" +
	"\apod_uid\x18\x05 \x01(\tR\x06podUid\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\"(\n" +
	"\x12PodPortForwardData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1a\n" +
	"\x18PodPortForwardCloseInput\"\x96\x02\n" +
	"\x12PodPortForwardExit\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fclient_bytes\x18\x04 \x01(\x04R\vclientBytes\x12\x1b\n" +
	"\tpod_bytes\x18\x05 \x01(\x04R\bpodBytes\x120\n" +
	"\x14client_limit_reached\x18\x06 \x01(\bR\x12clientLimitReached\x12*\n" +
	"\x11pod_limit_reached\x18\a \x01(\bR\x0fpodLimitReached\"\xdb\x01\n" +
	"\x13PodPortForwardFrame\x126\n" +
	"\x04data\x18\x01 \x01(\v2 .zke.agent.v1.PodPortForwardDataH\x00R\x04data\x12I\n" +
	"\vclose_input\x18\x02 \x01(\v2&.zke.agent.v1.PodPortForwardCloseInputH\x00R\n" +
	"closeInput\x126\n" +
	"\x04exit\x18\x03 \x01(\v2 .zke.agent.v1.PodPortForwardExitH\x00R\x04exitB\t\n" +
	"\amessageB0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_portforward_proto_rawDescOnce sync.Once
	file_api_agent_v1_portforward_proto_rawDescData []byte
)

func file_api_agent_v1_portforward_proto_rawDescGZIP() []byte {
	file_api_agent_v1_portforward_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_portforward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_portforward_proto_rawDesc), len(file_api_agent_v1_portforward_proto_rawDesc)))
	})
	return file_api_agent_v1_portforward_proto_rawDescData
}

var file_api_agent_v1_portforward_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_agent_v1_portforward_proto_goTypes = []any{
	(*PodPortForwardRequest)(nil),    // 0: zke.agent.v1.PodPortForwardRequest
	(*PodPortForwardResponse)(nil),   // 1: zke.agent.v1.PodPortForwardResponse
	(*PodPortForwardData)(nil),       // 2: zke.agent.v1.PodPortForwardData
	(*PodPortForwardCloseInput)(nil), // 3: zke.agent.v1.PodPortForwardCloseInput
	(*PodPortForwardExit)(nil),       // 4: zke.agent.v1.PodPortForwardExit
	(*PodPortForwardFrame)(nil),      // 5: zke.agent.v1.PodPortForwardFrame
	(ResultCode)(0),                  // 6: zke.agent.v1.ResultCode
}
var file_api_agent_v1_portforward_proto_depIdxs = []int32{
	6, // 0: zke.agent.v1.PodPortForwardResponse.result:type_name -> zke.agent.v1.ResultCode
	6, // 1: zke.agent.v1.PodPortForwardExit.result:type_name -> zke.agent.v1.ResultCode
	2, // 2: zke.agent.v1.PodPortForwardFrame.data:type_name -> zke.agent.v1.PodPortForwardData
	3, // 3: zke.agent.v1.PodPortForwardFrame.close_input:type_name -> zke.agent.v1.PodPortForwardCloseInput
	4, // 4: zke.agent.v1.PodPortForwardFrame.exit:type_name -> zke.agent.v1.PodPortForwardExit
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_agent_v1_portforward_proto_init() }
func file_api_agent_v1_portforward_proto_init() {
	if File_api_agent_v1_portforward_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	file_api_agent_v1_portforward_proto_msgTypes[5].OneofWrappers = []any{
		(*PodPortForwardFrame_Data)(nil),
		(*PodPortForwardFrame_CloseInput)(nil),
		(*PodPortForwardFrame_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_portforward_proto_rawDesc), len(file_api_agent_v1_portforward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_portforward_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_portforward_proto_depIdxs,
		MessageInfos:      file_api_agent_v1_portforward_proto_msgTypes,
	}.Build()
	File_api_agent_v1_portforward_proto = out.File
	file_api_agent_v1_portforward_proto_goTypes = nil
	file_api_agent_v1_portforward_proto_depIdxs = nil
}
