// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/resource.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceVerb int32

const (
	ResourceVerb_RESOURCE_VERB_UNSPECIFIED ResourceVerb = 0
	ResourceVerb_RESOURCE_VERB_LIST        ResourceVerb = 1
	ResourceVerb_RESOURCE_VERB_GET         ResourceVerb = 2
	ResourceVerb_RESOURCE_VERB_CREATE      ResourceVerb = 3
	ResourceVerb_RESOURCE_VERB_UPDATE      ResourceVerb = 4
	ResourceVerb_RESOURCE_VERB_PATCH       ResourceVerb = 5
	ResourceVerb_RESOURCE_VERB_DELETE      ResourceVerb = 6
	ResourceVerb_RESOURCE_VERB_DISCOVER    ResourceVerb = 7
)

// Enum value maps for ResourceVerb.
var (
	ResourceVerb_name = map[int32]string{
		0: "RESOURCE_VERB_UNSPECIFIED",
		1: "RESOURCE_VERB_LIST",
		2: "RESOURCE_VERB_GET",
		3: "RESOURCE_VERB_CREATE",
		4: "RESOURCE_VERB_UPDATE",
		5: "RESOURCE_VERB_PATCH",
		6: "RESOURCE_VERB_DELETE",
		7: "RESOURCE_VERB_DISCOVER",
	}
	ResourceVerb_value = map[string]int32{
		"RESOURCE_VERB_UNSPECIFIED": 0,
		"RESOURCE_VERB_LIST":        1,
		"RESOURCE_VERB_GET":         2,
		"RESOURCE_VERB_CREATE":      3,
		"RESOURCE_VERB_UPDATE":      4,
		"RESOURCE_VERB_PATCH":       5,
		"RESOURCE_VERB_DELETE":      6,
		"RESOURCE_VERB_DISCOVER":    7,
	}
)

func (x ResourceVerb) Enum() *ResourceVerb {
	p := new(ResourceVerb)
	*p = x
	return p
}

func (x ResourceVerb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceVerb) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_resource_proto_enumTypes[0].Descriptor()
}

func (ResourceVerb) Type() protoreflect.EnumType {
	return &file_api_agent_v1_resource_proto_enumTypes[0]
}

func (x ResourceVerb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceVerb.Descriptor instead.
func (ResourceVerb) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_resource_proto_rawDescGZIP(), []int{0}
}

type ResourceRepresentation int32

const (
	ResourceRepresentation_RESOURCE_REPRESENTATION_UNSPECIFIED ResourceRepresentation = 0
	ResourceRepresentation_RESOURCE_REPRESENTATION_TABLE       ResourceRepresentation = 1
	ResourceRepresentation_RESOURCE_REPRESENTATION_METADATA    ResourceRepresentation = 2
	ResourceRepresentation_RESOURCE_REPRESENTATION_FULL_OBJECT ResourceRepresentation = 3
)

// Enum value maps for ResourceRepresentation.
var (
	ResourceRepresentation_name = map[int32]string{
		0: "RESOURCE_REPRESENTATION_UNSPECIFIED",
		1: "RESOURCE_REPRESENTATION_TABLE",
		2: "RESOURCE_REPRESENTATION_METADATA",
		3: "RESOURCE_REPRESENTATION_FULL_OBJECT",
	}
	ResourceRepresentation_value = map[string]int32{
		"RESOURCE_REPRESENTATION_UNSPECIFIED": 0,
		"RESOURCE_REPRESENTATION_TABLE":       1,
		"RESOURCE_REPRESENTATION_METADATA":    2,
		"RESOURCE_REPRESENTATION_FULL_OBJECT": 3,
	}
)

func (x ResourceRepresentation) Enum() *ResourceRepresentation {
	p := new(ResourceRepresentation)
	*p = x
	return p
}

func (x ResourceRepresentation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceRepresentation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_resource_proto_enumTypes[1].Descriptor()
}

func (ResourceRepresentation) Type() protoreflect.EnumType {
	return &file_api_agent_v1_resource_proto_enumTypes[1]
}

func (x ResourceRepresentation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceRepresentation.Descriptor instead.
func (ResourceRepresentation) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_resource_proto_rawDescGZIP(), []int{1}
}

type PatchType int32

const (
	PatchType_PATCH_TYPE_UNSPECIFIED     PatchType = 0
	PatchType_PATCH_TYPE_JSON            PatchType = 1
	PatchType_PATCH_TYPE_MERGE           PatchType = 2
	PatchType_PATCH_TYPE_STRATEGIC_MERGE PatchType = 3
	PatchType_PATCH_TYPE_APPLY           PatchType = 4
)

// Enum value maps for PatchType.
var (
	PatchType_name = map[int32]string{
		0: "PATCH_TYPE_UNSPECIFIED",
		1: "PATCH_TYPE_JSON",
		2: "PATCH_TYPE_MERGE",
		3: "PATCH_TYPE_STRATEGIC_MERGE",
		4: "PATCH_TYPE_APPLY",
	}
	PatchType_value = map[string]int32{
		"PATCH_TYPE_UNSPECIFIED":     0,
		"PATCH_TYPE_JSON":            1,
		"PATCH_TYPE_MERGE":           2,
		"PATCH_TYPE_STRATEGIC_MERGE": 3,
		"PATCH_TYPE_APPLY":           4,
	}
)

func (x PatchType) Enum() *PatchType {
	p := new(PatchType)
	*p = x
	return p
}

func (x PatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_resource_proto_enumTypes[2].Descriptor()
}

func (PatchType) Type() protoreflect.EnumType {
	return &file_api_agent_v1_resource_proto_enumTypes[2]
}

func (x PatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PatchType.Descriptor instead.
func (PatchType) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_resource_proto_rawDescGZIP(), []int{2}
}

type GroupVersionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupVersionResource) Reset() {
	*x = GroupVersionResource{}
	mi := &file_api_agent_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupVersionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupVersionResource) ProtoMessage() {}

func (x *GroupVersionResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupVersionResource.ProtoReflect.Descriptor instead.
func (*GroupVersionResource) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *GroupVersionResource) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupVersionResource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GroupVersionResource) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type ListOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LabelSelector   string                 `protobuf:"bytes,1,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	FieldSelector   string                 `protobuf:"bytes,2,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	Limit           uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ContinueToken   string                 `protobuf:"bytes,4,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,5,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListOptions) Reset() {
	*x = ListOptions{}
	mi := &file_api_agent_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptions) ProtoMessage() {}

func (x *ListOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptions.ProtoReflect.Descriptor instead.
func (*ListOptions) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ListOptions) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *ListOptions) GetFieldSelector() string {
	if x != nil {
		return x.FieldSelector
	}
	return ""
}

func (x *ListOptions) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOptions) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

func (x *ListOptions) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

type ResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Verb           ResourceVerb           `protobuf:"varint,1,opt,name=verb,proto3,enum=zke.agent.v1.ResourceVerb" json:"verb,omitempty"`
	Resource       *GroupVersionResource  `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Namespace      string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Subresource    string                 `protobuf:"bytes,5,opt,name=subresource,proto3" json:"subresource,omitempty"`
	Representation ResourceRepresentation `protobuf:"varint,6,opt,name=representation,proto3,enum=zke.agent.v1.ResourceRepresentation" json:"representation,omitempty"`
	ListOptions    *ListOptions           `protobuf:"bytes,7,opt,name=list_options,json=listOptions,proto3" json:"list_options,omitempty"`
	PatchType      PatchType              `protobuf:"varint,8,opt,name=patch_type,json=patchType,proto3,enum=zke.agent.v1.PatchType" json:"patch_type,omitempty"`
	BodySize       uint64                 `protobuf:"varint,9,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_api_agent_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceRequest) GetVerb() ResourceVerb {
	if x != nil {
		return x.Verb
	}
	return ResourceVerb_RESOURCE_VERB_UNSPECIFIED
}

func (x *ResourceRequest) GetResource() *GroupVersionResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRequest) GetSubresource() string {
	if x != nil {
		return x.Subresource
	}
	return ""
}

func (x *ResourceRequest) GetRepresentation() ResourceRepresentation {
	if x != nil {
		return x.Representation
	}
	return ResourceRepresentation_RESOURCE_REPRESENTATION_UNSPECIFIED
}

func (x *ResourceRequest) GetListOptions() *ListOptions {
	if x != nil {
		return x.ListOptions
	}
	return nil
}

func (x *ResourceRequest) GetPatchType() PatchType {
	if x != nil {
		return x.PatchType
	}
	return PatchType_PATCH_TYPE_UNSPECIFIED
}

func (x *ResourceRequest) GetBodySize() uint64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

type ResourceResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ContentType          string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	BodySize             uint64                 `protobuf:"varint,6,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_api_agent_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *ResourceResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *ResourceResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ResourceResponse) GetBodySize() uint64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

var File_api_agent_v1_resource_proto protoreflect.FileDescriptor

const file_api_agent_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/agent/v1/resource.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"b\n" +
	"\x14GroupVersionResource\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\"\xc3\x01\n" +
	"\vListOptions\x12%\n" +
	"\x0elabel_selector\x18\x01 \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\x02 \x01(\tR\rfieldSelector\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12%\n" +
	"\x0econtinue_token\x18\x04 \x01(\tR\rcontinueToken\x12)\n" +
	"\x10resource_version\x18\x05 \x01(\tR\x0fresourceVersion\"\xb6\x03\n" +
	"\x0fResourceRequest\x12.\n" +
	"\x04verb\x18\x01 \x01(\x0e2\x1a.zke.agent.v1.ResourceVerbR\x04verb\x12>\n" +
	"\bresource\x18\x02 \x01(\v2\".zke.agent.v1.GroupVersionResourceR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vsubresource\x18\x05 \x01(\tR\vsubresource\x12L\n" +
	"\x0erepresentation\x18\x06 \x01(\x0e2$.zke.agent.v1.ResourceRepresentationR\x0erepresentation\x12<\n" +
	"\flist_options\x18\a \x01(\v2\x19.zke.agent.v1.ListOptionsR\vlistOptions\x126\n" +
	"\n" +
	"patch_type\x18\b \x01(\x0e2\x17.zke.agent.v1.PatchTypeR\tpatchType\x12\x1b\n" +
	"\tbody_size\x18\t \x01(\x04R\bbodySize\"\xec\x01\n" +
	"\x10ResourceResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tbody_size\x18\x06 \x01(\x04R\bbodySize*\xdf\x01\n" +
	"\fResourceVerb\x12\x1d\n" +
	"\x19RESOURCE_VERB_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESOURCE_VERB_LIST\x10\x01\x12\x15\n" +
	"\x11RESOURCE_VERB_GET\x10\x02\x12\x18\n" +
	"\x14RESOURCE_VERB_CREATE\x10\x03\x12\x18\n" +
	"\x14RESOURCE_VERB_UPDATE\x10\x04\x12\x17\n" +
	"\x13RESOURCE_VERB_PATCH\x10\x05\x12\x18\n" +
	"\x14RESOURCE_VERB_DELETE\x10\x06\x12\x1a\n" +
	"\x16RESOURCE_VERB_DISCOVER\x10\a*\xb3\x01\n" +
	"\x16ResourceRepresentation\x12'\n" +
	"#RESOURCE_REPRESENTATION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dRESOURCE_REPRESENTATION_TABLE\x10\x01\x12$\n" +
	" RESOURCE_REPRESENTATION_METADATA\x10\x02\x12'\n" +
	"#RESOURCE_REPRESENTATION_FULL_OBJECT\x10\x03*\x88\x01\n" +
	"\tPatchType\x12\x1a\n" +
	"\x16PATCH_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPATCH_TYPE_JSON\x10\x01\x12\x14\n" +
	"\x10PATCH_TYPE_MERGE\x10\x02\x12\x1e\n" +
	"\x1aPATCH_TYPE_STRATEGIC_MERGE\x10\x03\x12\x14\n" +
	"\x10PATCH_TYPE_APPLY\x10\x04B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_resource_proto_rawDescOnce sync.Once
	file_api_agent_v1_resource_proto_rawDescData []byte
)

func file_api_agent_v1_resource_proto_rawDescGZIP() []byte {
	file_api_agent_v1_resource_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_resource_proto_rawDesc), len(file_api_agent_v1_resource_proto_rawDesc)))
	})
	return file_api_agent_v1_resource_proto_rawDescData
}

var file_api_agent_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_agent_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_agent_v1_resource_proto_goTypes = []any{
	(ResourceVerb)(0),            // 0: zke.agent.v1.ResourceVerb
	(ResourceRepresentation)(0),  // 1: zke.agent.v1.ResourceRepresentation
	(PatchType)(0),               // 2: zke.agent.v1.PatchType
	(*GroupVersionResource)(nil), // 3: zke.agent.v1.GroupVersionResource
	(*ListOptions)(nil),          // 4: zke.agent.v1.ListOptions
	(*ResourceRequest)(nil),      // 5: zke.agent.v1.ResourceRequest
	(*ResourceResponse)(nil),     // 6: zke.agent.v1.ResourceResponse
	(ResultCode)(0),              // 7: zke.agent.v1.ResultCode
}
var file_api_agent_v1_resource_proto_depIdxs = []int32{
	0, // 0: zke.agent.v1.ResourceRequest.verb:type_name -> zke.agent.v1.ResourceVerb
	3, // 1: zke.agent.v1.ResourceRequest.resource:type_name -> zke.agent.v1.GroupVersionResource
	1, // 2: zke.agent.v1.ResourceRequest.representation:type_name -> zke.agent.v1.ResourceRepresentation
	4, // 3: zke.agent.v1.ResourceRequest.list_options:type_name -> zke.agent.v1.ListOptions
	2, // 4: zke.agent.v1.ResourceRequest.patch_type:type_name -> zke.agent.v1.PatchType
	7, // 5: zke.agent.v1.ResourceResponse.result:type_name -> zke.agent.v1.ResultCode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_agent_v1_resource_proto_init() }
func file_api_agent_v1_resource_proto_init() {
	if File_api_agent_v1_resource_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_resource_proto_rawDesc), len(file_api_agent_v1_resource_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_resource_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_resource_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_resource_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_resource_proto_msgTypes,
	}.Build()
	File_api_agent_v1_resource_proto = out.File
	file_api_agent_v1_resource_proto_goTypes = nil
	file_api_agent_v1_resource_proto_depIdxs = nil
}
