// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/stream.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamKind int32

const (
	StreamKind_STREAM_KIND_UNSPECIFIED      StreamKind = 0
	StreamKind_STREAM_KIND_RESOURCE         StreamKind = 10
	StreamKind_STREAM_KIND_RESOURCE_WATCH   StreamKind = 11
	StreamKind_STREAM_KIND_POD_LOGS         StreamKind = 20
	StreamKind_STREAM_KIND_POD_EXEC         StreamKind = 21
	StreamKind_STREAM_KIND_POD_PORT_FORWARD StreamKind = 22
	StreamKind_STREAM_KIND_TERMINAL_SESSION StreamKind = 30
	// Opened by the Agent, not the Server.
	StreamKind_STREAM_KIND_METRICS_INGEST    StreamKind = 40
	StreamKind_STREAM_KIND_METRICS_COLLECTOR StreamKind = 41
)

// Enum value maps for StreamKind.
var (
	StreamKind_name = map[int32]string{
		0:  "STREAM_KIND_UNSPECIFIED",
		10: "STREAM_KIND_RESOURCE",
		11: "STREAM_KIND_RESOURCE_WATCH",
		20: "STREAM_KIND_POD_LOGS",
		21: "STREAM_KIND_POD_EXEC",
		22: "STREAM_KIND_POD_PORT_FORWARD",
		30: "STREAM_KIND_TERMINAL_SESSION",
		40: "STREAM_KIND_METRICS_INGEST",
		41: "STREAM_KIND_METRICS_COLLECTOR",
	}
	StreamKind_value = map[string]int32{
		"STREAM_KIND_UNSPECIFIED":       0,
		"STREAM_KIND_RESOURCE":          10,
		"STREAM_KIND_RESOURCE_WATCH":    11,
		"STREAM_KIND_POD_LOGS":          20,
		"STREAM_KIND_POD_EXEC":          21,
		"STREAM_KIND_POD_PORT_FORWARD":  22,
		"STREAM_KIND_TERMINAL_SESSION":  30,
		"STREAM_KIND_METRICS_INGEST":    40,
		"STREAM_KIND_METRICS_COLLECTOR": 41,
	}
)

func (x StreamKind) Enum() *StreamKind {
	p := new(StreamKind)
	*p = x
	return p
}

func (x StreamKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_stream_proto_enumTypes[0].Descriptor()
}

func (StreamKind) Type() protoreflect.EnumType {
	return &file_api_agent_v1_stream_proto_enumTypes[0]
}

func (x StreamKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamKind.Descriptor instead.
func (StreamKind) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_stream_proto_rawDescGZIP(), []int{0}
}

type ResultCode int32

const (
	ResultCode_RESULT_CODE_UNSPECIFIED        ResultCode = 0
	ResultCode_RESULT_CODE_OK                 ResultCode = 1
	ResultCode_RESULT_CODE_INVALID_ARGUMENT   ResultCode = 2
	ResultCode_RESULT_CODE_UNAUTHENTICATED    ResultCode = 3
	ResultCode_RESULT_CODE_FORBIDDEN          ResultCode = 4
	ResultCode_RESULT_CODE_NOT_FOUND          ResultCode = 5
	ResultCode_RESULT_CODE_CONFLICT           ResultCode = 6
	ResultCode_RESULT_CODE_RESOURCE_EXHAUSTED ResultCode = 7
	ResultCode_RESULT_CODE_UNAVAILABLE        ResultCode = 8
	ResultCode_RESULT_CODE_TIMEOUT            ResultCode = 9
	ResultCode_RESULT_CODE_CANCELED           ResultCode = 10
	ResultCode_RESULT_CODE_INTERNAL           ResultCode = 11
)

// Enum value maps for ResultCode.
var (
	ResultCode_name = map[int32]string{
		0:  "RESULT_CODE_UNSPECIFIED",
		1:  "RESULT_CODE_OK",
		2:  "RESULT_CODE_INVALID_ARGUMENT",
		3:  "RESULT_CODE_UNAUTHENTICATED",
		4:  "RESULT_CODE_FORBIDDEN",
		5:  "RESULT_CODE_NOT_FOUND",
		6:  "RESULT_CODE_CONFLICT",
		7:  "RESULT_CODE_RESOURCE_EXHAUSTED",
		8:  "RESULT_CODE_UNAVAILABLE",
		9:  "RESULT_CODE_TIMEOUT",
		10: "RESULT_CODE_CANCELED",
		11: "RESULT_CODE_INTERNAL",
	}
	ResultCode_value = map[string]int32{
		"RESULT_CODE_UNSPECIFIED":        0,
		"RESULT_CODE_OK":                 1,
		"RESULT_CODE_INVALID_ARGUMENT":   2,
		"RESULT_CODE_UNAUTHENTICATED":    3,
		"RESULT_CODE_FORBIDDEN":          4,
		"RESULT_CODE_NOT_FOUND":          5,
		"RESULT_CODE_CONFLICT":           6,
		"RESULT_CODE_RESOURCE_EXHAUSTED": 7,
		"RESULT_CODE_UNAVAILABLE":        8,
		"RESULT_CODE_TIMEOUT":            9,
		"RESULT_CODE_CANCELED":           10,
		"RESULT_CODE_INTERNAL":           11,
	}
)

func (x ResultCode) Enum() *ResultCode {
	p := new(ResultCode)
	*p = x
	return p
}

func (x ResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_stream_proto_enumTypes[1].Descriptor()
}

func (ResultCode) Type() protoreflect.EnumType {
	return &file_api_agent_v1_stream_proto_enumTypes[1]
}

func (x ResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultCode.Descriptor instead.
func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_stream_proto_rawDescGZIP(), []int{1}
}

type StreamHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Kind            StreamKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=zke.agent.v1.StreamKind" json:"kind,omitempty"`
	RequestId       string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimeoutMillis   uint64                 `protobuf:"varint,4,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamHeader) Reset() {
	*x = StreamHeader{}
	mi := &file_api_agent_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeader) ProtoMessage() {}

func (x *StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeader.ProtoReflect.Descriptor instead.
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamHeader) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *StreamHeader) GetKind() StreamKind {
	if x != nil {
		return x.Kind
	}
	return StreamKind_STREAM_KIND_UNSPECIFIED
}

func (x *StreamHeader) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamHeader) GetTimeoutMillis() uint64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *StreamHeader) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

var File_api_agent_v1_stream_proto protoreflect.FileDescriptor

const file_api_agent_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x19api/agent/v1/stream.proto\x12\fzke.agent.v1\"\xd6\x01\n" +
	"\fStreamHeader\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x18.zke.agent.v1.StreamKindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12%\n" +
	"\x0etimeout_millis\x18\x04 \x01(\x04R\rtimeoutMillis\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey*\x9e\x02\n" +
	"\n" +
	"StreamKind\x12\x1b\n" +
	"\x17STREAM_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STREAM_KIND_RESOURCE\x10\n" +
	"\x12\x1e\n" +
	"\x1aSTREAM_KIND_RESOURCE_WATCH\x10\v\x12\x18\n" +
	"\x14STREAM_KIND_POD_LOGS\x10\x14\x12\x18\n" +
	"\x14STREAM_KIND_POD_EXEC\x10\x15\x12 \n" +
	"\x1cSTREAM_KIND_POD_PORT_FORWARD\x10\x16\x12 \n" +
	"\x1cSTREAM_KIND_TERMINAL_SESSION\x10\x1e\x12\x1e\n" +
	"\x1aSTREAM_KIND_METRICS_INGEST\x10(\x12!\n" +
	"\x1dSTREAM_KIND_METRICS_COLLECTOR\x10)*\xde\x02\n" +
	"\n" +
	"ResultCode\x12\x1b\n" +
	"\x17RESULT_CODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRESULT_CODE_OK\x10\x01\x12 \n" +
	"\x1cRESULT_CODE_INVALID_ARGUMENT\x10\x02\x12\x1f\n" +
	"\x1bRESULT_CODE_UNAUTHENTICATED\x10\x03\x12\x19\n" +
	"\x15RESULT_CODE_FORBIDDEN\x10\x04\x12\x19\n" +
	"\x15RESULT_CODE_NOT_FOUND\x10\x05\x12\x18\n" +
	"\x14RESULT_CODE_CONFLICT\x10\x06\x12\"\n" +
	"\x1eRESULT_CODE_RESOURCE_EXHAUSTED\x10\a\x12\x1b\n" +
	"\x17RESULT_CODE_UNAVAILABLE\x10\b\x12\x17\n" +
	"\x13RESULT_CODE_TIMEOUT\x10\t\x12\x18\n" +
	"\x14RESULT_CODE_CANCELED\x10\n" +
	"\x12\x18\n" +
	"\x14RESULT_CODE_INTERNAL\x10\vB0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_stream_proto_rawDescOnce sync.Once
	file_api_agent_v1_stream_proto_rawDescData []byte
)

func file_api_agent_v1_stream_proto_rawDescGZIP() []byte {
	file_api_agent_v1_stream_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_stream_proto_rawDesc), len(file_api_agent_v1_stream_proto_rawDesc)))
	})
	return file_api_agent_v1_stream_proto_rawDescData
}

var file_api_agent_v1_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_agent_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_agent_v1_stream_proto_goTypes = []any{
	(StreamKind)(0),      // 0: zke.agent.v1.StreamKind
	(ResultCode)(0),      // 1: zke.agent.v1.ResultCode
	(*StreamHeader)(nil), // 2: zke.agent.v1.StreamHeader
}
var file_api_agent_v1_stream_proto_depIdxs = []int32{
	0, // 0: zke.agent.v1.StreamHeader.kind:type_name -> zke.agent.v1.StreamKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_agent_v1_stream_proto_init() }
func file_api_agent_v1_stream_proto_init() {
	if File_api_agent_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_stream_proto_rawDesc), len(file_api_agent_v1_stream_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_stream_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_stream_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_stream_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_stream_proto_msgTypes,
	}.Build()
	File_api_agent_v1_stream_proto = out.File
	file_api_agent_v1_stream_proto_goTypes = nil
	file_api_agent_v1_stream_proto_depIdxs = nil
}
