// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/terminal.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminalSessionAction int32

const (
	TerminalSessionAction_TERMINAL_SESSION_ACTION_UNSPECIFIED TerminalSessionAction = 0
	TerminalSessionAction_TERMINAL_SESSION_ACTION_CREATE      TerminalSessionAction = 1
	TerminalSessionAction_TERMINAL_SESSION_ACTION_DELETE      TerminalSessionAction = 2
)

// Enum value maps for TerminalSessionAction.
var (
	TerminalSessionAction_name = map[int32]string{
		0: "TERMINAL_SESSION_ACTION_UNSPECIFIED",
		1: "TERMINAL_SESSION_ACTION_CREATE",
		2: "TERMINAL_SESSION_ACTION_DELETE",
	}
	TerminalSessionAction_value = map[string]int32{
		"TERMINAL_SESSION_ACTION_UNSPECIFIED": 0,
		"TERMINAL_SESSION_ACTION_CREATE":      1,
		"TERMINAL_SESSION_ACTION_DELETE":      2,
	}
)

func (x TerminalSessionAction) Enum() *TerminalSessionAction {
	p := new(TerminalSessionAction)
	*p = x
	return p
}

func (x TerminalSessionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalSessionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_terminal_proto_enumTypes[0].Descriptor()
}

func (TerminalSessionAction) Type() protoreflect.EnumType {
	return &file_api_agent_v1_terminal_proto_enumTypes[0]
}

func (x TerminalSessionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalSessionAction.Descriptor instead.
func (TerminalSessionAction) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_terminal_proto_rawDescGZIP(), []int{0}
}

type TerminalSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          TerminalSessionAction  `protobuf:"varint,1,opt,name=action,proto3,enum=zke.agent.v1.TerminalSessionAction" json:"action,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Namespace       string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Permissions     []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	TtlSeconds      uint64                 `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Image           string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullPolicy string                 `protobuf:"bytes,8,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	// How much of the Cluster one session Pod may take. The Agent used to hold
	// these as constants, which made the budget of a workload running in the
	// operator's own Cluster the one thing about it they could not change.
	//
	// An empty quantity means the entry is left off the container: Kubernetes has
	// no other spelling for "no limit", and a Namespace governed by a LimitRange
	// needs to be able to defer to it.
	CpuRequest    string `protobuf:"bytes,9,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	MemoryRequest string `protobuf:"bytes,10,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	CpuLimit      string `protobuf:"bytes,11,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   string `protobuf:"bytes,12,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSessionRequest) Reset() {
	*x = TerminalSessionRequest{}
	mi := &file_api_agent_v1_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSessionRequest) ProtoMessage() {}

func (x *TerminalSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminalSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *TerminalSessionRequest) GetAction() TerminalSessionAction {
	if x != nil {
		return x.Action
	}
	return TerminalSessionAction_TERMINAL_SESSION_ACTION_UNSPECIFIED
}

func (x *TerminalSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TerminalSessionRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TerminalSessionRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *TerminalSessionRequest) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *TerminalSessionRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TerminalSessionRequest) GetImagePullPolicy() string {
	if x != nil {
		return x.ImagePullPolicy
	}
	return ""
}

func (x *TerminalSessionRequest) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *TerminalSessionRequest) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *TerminalSessionRequest) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *TerminalSessionRequest) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type TerminalSessionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode uint32                 `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	SessionId            string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Namespace            string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName              string                 `protobuf:"bytes,7,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid               string                 `protobuf:"bytes,8,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Container            string                 `protobuf:"bytes,9,opt,name=container,proto3" json:"container,omitempty"`
	ExpiresAtUnix        int64                  `protobuf:"varint,10,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TerminalSessionResponse) Reset() {
	*x = TerminalSessionResponse{}
	mi := &file_api_agent_v1_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSessionResponse) ProtoMessage() {}

func (x *TerminalSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSessionResponse.ProtoReflect.Descriptor instead.
func (*TerminalSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *TerminalSessionResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *TerminalSessionResponse) GetKubernetesStatusCode() uint32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *TerminalSessionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TerminalSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TerminalSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalSessionResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TerminalSessionResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *TerminalSessionResponse) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *TerminalSessionResponse) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *TerminalSessionResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_api_agent_v1_terminal_proto protoreflect.FileDescriptor

const file_api_agent_v1_terminal_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/agent/v1/terminal.proto\x12\fzke.agent.v1\x1a\x19api/agent/v1/stream.proto\"\xb8\x03\n" +
	"\x16TerminalSessionRequest\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.zke.agent.v1.TerminalSessionActionR\x06action\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\x04R\n" +
	"ttlSeconds\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12*\n" +
	"\x11image_pull_policy\x18\b \x01(\tR\x0fimagePullPolicy\x12\x1f\n" +
	"\vcpu_request\x18\t \x01(\tR\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\n" +
	" \x01(\tR\rmemoryRequest\x12\x1b\n" +
	"\tcpu_limit\x18\v \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\f \x01(\tR\vmemoryLimit\"\xea\x02\n" +
	"\x17TerminalSessionResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\rR\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\a \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\b \x01(\tR\x06podUid\x12\x1c\n" +
	"\tcontainer\x18\t \x01(\tR\tcontainer\x12&\n" +
	"\x0fexpires_at_unix\x18\n" +
	" \x01(\x03R\rexpiresAtUnix*\x88\x01\n" +
	"\x15TerminalSessionAction\x12'\n" +
	"#TERMINAL_SESSION_ACTION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTERMINAL_SESSION_ACTION_CREATE\x10\x01\x12\"\n" +
	"\x1eTERMINAL_SESSION_ACTION_DELETE\x10\x02B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_terminal_proto_rawDescOnce sync.Once
	file_api_agent_v1_terminal_proto_rawDescData []byte
)

func file_api_agent_v1_terminal_proto_rawDescGZIP() []byte {
	file_api_agent_v1_terminal_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_terminal_proto_rawDesc), len(file_api_agent_v1_terminal_proto_rawDesc)))
	})
	return file_api_agent_v1_terminal_proto_rawDescData
}

var file_api_agent_v1_terminal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_agent_v1_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_agent_v1_terminal_proto_goTypes = []any{
	(TerminalSessionAction)(0),      // 0: zke.agent.v1.TerminalSessionAction
	(*TerminalSessionRequest)(nil),  // 1: zke.agent.v1.TerminalSessionRequest
	(*TerminalSessionResponse)(nil), // 2: zke.agent.v1.TerminalSessionResponse
	(ResultCode)(0),                 // 3: zke.agent.v1.ResultCode
}
var file_api_agent_v1_terminal_proto_depIdxs = []int32{
	0, // 0: zke.agent.v1.TerminalSessionRequest.action:type_name -> zke.agent.v1.TerminalSessionAction
	3, // 1: zke.agent.v1.TerminalSessionResponse.result:type_name -> zke.agent.v1.ResultCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_agent_v1_terminal_proto_init() }
func file_api_agent_v1_terminal_proto_init() {
	if File_api_agent_v1_terminal_proto != nil {
		return
	}
	file_api_agent_v1_stream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_terminal_proto_rawDesc), len(file_api_agent_v1_terminal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_terminal_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_terminal_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_terminal_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_terminal_proto_msgTypes,
	}.Build()
	File_api_agent_v1_terminal_proto = out.File
	file_api_agent_v1_terminal_proto_goTypes = nil
	file_api_agent_v1_terminal_proto_depIdxs = nil
}
