// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: api/agent/v1/watch.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceWatchEventType int32

const (
	ResourceWatchEventType_RESOURCE_WATCH_EVENT_TYPE_UNSPECIFIED ResourceWatchEventType = 0
	ResourceWatchEventType_RESOURCE_WATCH_EVENT_TYPE_ADDED       ResourceWatchEventType = 1
	ResourceWatchEventType_RESOURCE_WATCH_EVENT_TYPE_MODIFIED    ResourceWatchEventType = 2
	ResourceWatchEventType_RESOURCE_WATCH_EVENT_TYPE_DELETED     ResourceWatchEventType = 3
	ResourceWatchEventType_RESOURCE_WATCH_EVENT_TYPE_BOOKMARK    ResourceWatchEventType = 4
)

// Enum value maps for ResourceWatchEventType.
var (
	ResourceWatchEventType_name = map[int32]string{
		0: "RESOURCE_WATCH_EVENT_TYPE_UNSPECIFIED",
		1: "RESOURCE_WATCH_EVENT_TYPE_ADDED",
		2: "RESOURCE_WATCH_EVENT_TYPE_MODIFIED",
		3: "RESOURCE_WATCH_EVENT_TYPE_DELETED",
		4: "RESOURCE_WATCH_EVENT_TYPE_BOOKMARK",
	}
	ResourceWatchEventType_value = map[string]int32{
		"RESOURCE_WATCH_EVENT_TYPE_UNSPECIFIED": 0,
		"RESOURCE_WATCH_EVENT_TYPE_ADDED":       1,
		"RESOURCE_WATCH_EVENT_TYPE_MODIFIED":    2,
		"RESOURCE_WATCH_EVENT_TYPE_DELETED":     3,
		"RESOURCE_WATCH_EVENT_TYPE_BOOKMARK":    4,
	}
)

func (x ResourceWatchEventType) Enum() *ResourceWatchEventType {
	p := new(ResourceWatchEventType)
	*p = x
	return p
}

func (x ResourceWatchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceWatchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_watch_proto_enumTypes[0].Descriptor()
}

func (ResourceWatchEventType) Type() protoreflect.EnumType {
	return &file_api_agent_v1_watch_proto_enumTypes[0]
}

func (x ResourceWatchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceWatchEventType.Descriptor instead.
func (ResourceWatchEventType) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_watch_proto_rawDescGZIP(), []int{0}
}

type ResourceWatchRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Resource             *GroupVersionResource  `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Namespace            string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FieldSelector        string                 `protobuf:"bytes,3,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	ResourceVersion      string                 `protobuf:"bytes,4,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	IncludeInitialEvents bool                   `protobuf:"varint,5,opt,name=include_initial_events,json=includeInitialEvents,proto3" json:"include_initial_events,omitempty"`
	Follow               bool                   `protobuf:"varint,6,opt,name=follow,proto3" json:"follow,omitempty"`
	InitialEventLimit    uint32                 `protobuf:"varint,7,opt,name=initial_event_limit,json=initialEventLimit,proto3" json:"initial_event_limit,omitempty"`
	AllowWatchBookmarks  bool                   `protobuf:"varint,8,opt,name=allow_watch_bookmarks,json=allowWatchBookmarks,proto3" json:"allow_watch_bookmarks,omitempty"`
	MaxEventBytes        uint64                 `protobuf:"varint,9,opt,name=max_event_bytes,json=maxEventBytes,proto3" json:"max_event_bytes,omitempty"`
	MaxTotalBytes        uint64                 `protobuf:"varint,10,opt,name=max_total_bytes,json=maxTotalBytes,proto3" json:"max_total_bytes,omitempty"`
	MaxEvents            uint64                 `protobuf:"varint,11,opt,name=max_events,json=maxEvents,proto3" json:"max_events,omitempty"`
	// Set only by the Server's cluster-wide Kubernetes Event route, and honoured
	// only for core/v1 Events. Without it the Agent keeps refusing an empty
	// Namespace for anything but the exact Node UID snapshot a describe needs, so
	// an Agent that predates this field simply refuses — which is the behaviour a
	// Server upgraded ahead of its Agents should get.
	ClusterEventAccess bool `protobuf:"varint,12,opt,name=cluster_event_access,json=clusterEventAccess,proto3" json:"cluster_event_access,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceWatchRequest) Reset() {
	*x = ResourceWatchRequest{}
	mi := &file_api_agent_v1_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWatchRequest) ProtoMessage() {}

func (x *ResourceWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWatchRequest.ProtoReflect.Descriptor instead.
func (*ResourceWatchRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_watch_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceWatchRequest) GetResource() *GroupVersionResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceWatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceWatchRequest) GetFieldSelector() string {
	if x != nil {
		return x.FieldSelector
	}
	return ""
}

func (x *ResourceWatchRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ResourceWatchRequest) GetIncludeInitialEvents() bool {
	if x != nil {
		return x.IncludeInitialEvents
	}
	return false
}

func (x *ResourceWatchRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *ResourceWatchRequest) GetInitialEventLimit() uint32 {
	if x != nil {
		return x.InitialEventLimit
	}
	return 0
}

func (x *ResourceWatchRequest) GetAllowWatchBookmarks() bool {
	if x != nil {
		return x.AllowWatchBookmarks
	}
	return false
}

func (x *ResourceWatchRequest) GetMaxEventBytes() uint64 {
	if x != nil {
		return x.MaxEventBytes
	}
	return 0
}

func (x *ResourceWatchRequest) GetMaxTotalBytes() uint64 {
	if x != nil {
		return x.MaxTotalBytes
	}
	return 0
}

func (x *ResourceWatchRequest) GetMaxEvents() uint64 {
	if x != nil {
		return x.MaxEvents
	}
	return 0
}

func (x *ResourceWatchRequest) GetClusterEventAccess() bool {
	if x != nil {
		return x.ClusterEventAccess
	}
	return false
}

type ResourceWatchResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Result                 ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode   int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason                 string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message                string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ContentType            string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ResourceVersion        string                 `protobuf:"bytes,6,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	InitialEventsTruncated bool                   `protobuf:"varint,7,opt,name=initial_events_truncated,json=initialEventsTruncated,proto3" json:"initial_events_truncated,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResourceWatchResponse) Reset() {
	*x = ResourceWatchResponse{}
	mi := &file_api_agent_v1_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWatchResponse) ProtoMessage() {}

func (x *ResourceWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWatchResponse.ProtoReflect.Descriptor instead.
func (*ResourceWatchResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_watch_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceWatchResponse) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *ResourceWatchResponse) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *ResourceWatchResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResourceWatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceWatchResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ResourceWatchResponse) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ResourceWatchResponse) GetInitialEventsTruncated() bool {
	if x != nil {
		return x.InitialEventsTruncated
	}
	return false
}

type ResourceWatchEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            ResourceWatchEventType `protobuf:"varint,1,opt,name=type,proto3,enum=zke.agent.v1.ResourceWatchEventType" json:"type,omitempty"`
	Object          []byte                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceWatchEvent) Reset() {
	*x = ResourceWatchEvent{}
	mi := &file_api_agent_v1_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWatchEvent) ProtoMessage() {}

func (x *ResourceWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWatchEvent.ProtoReflect.Descriptor instead.
func (*ResourceWatchEvent) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_watch_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceWatchEvent) GetType() ResourceWatchEventType {
	if x != nil {
		return x.Type
	}
	return ResourceWatchEventType_RESOURCE_WATCH_EVENT_TYPE_UNSPECIFIED
}

func (x *ResourceWatchEvent) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *ResourceWatchEvent) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

type ResourceWatchTrailer struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               ResultCode             `protobuf:"varint,1,opt,name=result,proto3,enum=zke.agent.v1.ResultCode" json:"result,omitempty"`
	KubernetesStatusCode int32                  `protobuf:"varint,2,opt,name=kubernetes_status_code,json=kubernetesStatusCode,proto3" json:"kubernetes_status_code,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	EventsSent           uint64                 `protobuf:"varint,5,opt,name=events_sent,json=eventsSent,proto3" json:"events_sent,omitempty"`
	BytesSent            uint64                 `protobuf:"varint,6,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	LastResourceVersion  string                 `protobuf:"bytes,7,opt,name=last_resource_version,json=lastResourceVersion,proto3" json:"last_resource_version,omitempty"`
	LimitReached         bool                   `protobuf:"varint,8,opt,name=limit_reached,json=limitReached,proto3" json:"limit_reached,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceWatchTrailer) Reset() {
	*x = ResourceWatchTrailer{}
	mi := &file_api_agent_v1_watch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWatchTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWatchTrailer) ProtoMessage() {}

func (x *ResourceWatchTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_watch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWatchTrailer.ProtoReflect.Descriptor instead.
func (*ResourceWatchTrailer) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_watch_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceWatchTrailer) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *ResourceWatchTrailer) GetKubernetesStatusCode() int32 {
	if x != nil {
		return x.KubernetesStatusCode
	}
	return 0
}

func (x *ResourceWatchTrailer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResourceWatchTrailer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceWatchTrailer) GetEventsSent() uint64 {
	if x != nil {
		return x.EventsSent
	}
	return 0
}

func (x *ResourceWatchTrailer) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ResourceWatchTrailer) GetLastResourceVersion() string {
	if x != nil {
		return x.LastResourceVersion
	}
	return ""
}

func (x *ResourceWatchTrailer) GetLimitReached() bool {
	if x != nil {
		return x.LimitReached
	}
	return false
}

type ResourceWatchFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ResourceWatchFrame_Event
	//	*ResourceWatchFrame_Trailer
	Message       isResourceWatchFrame_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceWatchFrame) Reset() {
	*x = ResourceWatchFrame{}
	mi := &file_api_agent_v1_watch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWatchFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWatchFrame) ProtoMessage() {}

func (x *ResourceWatchFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_watch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWatchFrame.ProtoReflect.Descriptor instead.
func (*ResourceWatchFrame) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_watch_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceWatchFrame) GetMessage() isResourceWatchFrame_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ResourceWatchFrame) GetEvent() *ResourceWatchEvent {
	if x != nil {
		if x, ok := x.Message.(*ResourceWatchFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ResourceWatchFrame) GetTrailer() *ResourceWatchTrailer {
	if x != nil {
		if x, ok := x.Message.(*ResourceWatchFrame_Trailer); ok {
			return x.Trailer
		}
	}
	return nil
}

type isResourceWatchFrame_Message interface {
	isResourceWatchFrame_Message()
}

type ResourceWatchFrame_Event struct {
	Event *ResourceWatchEvent `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type ResourceWatchFrame_Trailer struct {
	Trailer *ResourceWatchTrailer `protobuf:"bytes,2,opt,name=trailer,proto3,oneof"`
}

func (*ResourceWatchFrame_Event) isResourceWatchFrame_Message() {}

func (*ResourceWatchFrame_Trailer) isResourceWatchFrame_Message() {}

var File_api_agent_v1_watch_proto protoreflect.FileDescriptor

const file_api_agent_v1_watch_proto_rawDesc = "" +
	"\n" +
	"\x18api/agent/v1/watch.proto\x12\fzke.agent.v1\x1a\x1bapi/agent/v1/resource.proto\x1a\x19api/agent/v1/stream.proto\"\x99\x04\n" +
	"\x14ResourceWatchRequest\x12>\n" +
	"\bresource\x18\x01 \x01(\v2\".zke.agent.v1.GroupVersionResourceR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0efield_selector\x18\x03 \x01(\tR\rfieldSelector\x12)\n" +
	"\x10resource_version\x18\x04 \x01(\tR\x0fresourceVersion\x124\n" +
	"\x16include_initial_events\x18\x05 \x01(\bR\x14includeInitialEvents\x12\x16\n" +
	"\x06follow\x18\x06 \x01(\bR\x06follow\x12.\n" +
	"\x13initial_event_limit\x18\a \x01(\rR\x11initialEventLimit\x122\n" +
	"\x15allow_watch_bookmarks\x18\b \x01(\bR\x13allowWatchBookmarks\x12&\n" +
	"\x0fmax_event_bytes\x18\t \x01(\x04R\rmaxEventBytes\x12&\n" +
	"\x0fmax_total_bytes\x18\n" +
	" \x01(\x04R\rmaxTotalBytes\x12\x1d\n" +
	"\n" +
	"max_events\x18\v \x01(\x04R\tmaxEvents\x120\n" +
	"\x14cluster_event_access\x18\f \x01(\bR\x12clusterEventAccess\"\xb9\x02\n" +
	"\x15ResourceWatchResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12)\n" +
	"\x10resource_version\x18\x06 \x01(\tR\x0fresourceVersion\x128\n" +
	"\x18initial_events_truncated\x18\a \x01(\bR\x16initialEventsTruncated\"\x91\x01\n" +
	"\x12ResourceWatchEvent\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.zke.agent.v1.ResourceWatchEventTypeR\x04type\x12\x16\n" +
	"\x06object\x18\x02 \x01(\fR\x06object\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\tR\x0fresourceVersion\"\xc9\x02\n" +
	"\x14ResourceWatchTrailer\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.zke.agent.v1.ResultCodeR\x06result\x124\n" +
	"\x16kubernetes_status_code\x18\x02 \x01(\x05R\x14kubernetesStatusCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vevents_sent\x18\x05 \x01(\x04R\n" +
	"eventsSent\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x06 \x01(\x04R\tbytesSent\x122\n" +
	"\x15last_resource_version\x18\a \x01(\tR\x13lastResourceVersion\x12#\n" +
	"\rlimit_reached\x18\b \x01(\bR\flimitReached\"\x99\x01\n" +
	"\x12ResourceWatchFrame\x128\n" +
	"\x05event\x18\x01 \x01(\v2 .zke.agent.v1.ResourceWatchEventH\x00R\x05event\x12>\n" +
	"\atrailer\x18\x02 \x01(\v2\".zke.agent.v1.ResourceWatchTrailerH\x00R\atrailerB\t\n" +
	"\amessage*\xdf\x01\n" +
	"\x16ResourceWatchEventType\x12)\n" +
	"%RESOURCE_WATCH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fRESOURCE_WATCH_EVENT_TYPE_ADDED\x10\x01\x12&\n" +
	"\"RESOURCE_WATCH_EVENT_TYPE_MODIFIED\x10\x02\x12%\n" +
	"!RESOURCE_WATCH_EVENT_TYPE_DELETED\x10\x03\x12&\n" +
	"\"RESOURCE_WATCH_EVENT_TYPE_BOOKMARK\x10\x04B0Z.github.com/togettoyou/zke/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_watch_proto_rawDescOnce sync.Once
	file_api_agent_v1_watch_proto_rawDescData []byte
)

func file_api_agent_v1_watch_proto_rawDescGZIP() []byte {
	file_api_agent_v1_watch_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_watch_proto_rawDesc), len(file_api_agent_v1_watch_proto_rawDesc)))
	})
	return file_api_agent_v1_watch_proto_rawDescData
}

var file_api_agent_v1_watch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_agent_v1_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_agent_v1_watch_proto_goTypes = []any{
	(ResourceWatchEventType)(0),   // 0: zke.agent.v1.ResourceWatchEventType
	(*ResourceWatchRequest)(nil),  // 1: zke.agent.v1.ResourceWatchRequest
	(*ResourceWatchResponse)(nil), // 2: zke.agent.v1.ResourceWatchResponse
	(*ResourceWatchEvent)(nil),    // 3: zke.agent.v1.ResourceWatchEvent
	(*ResourceWatchTrailer)(nil),  // 4: zke.agent.v1.ResourceWatchTrailer
	(*ResourceWatchFrame)(nil),    // 5: zke.agent.v1.ResourceWatchFrame
	(*GroupVersionResource)(nil),  // 6: zke.agent.v1.GroupVersionResource
	(ResultCode)(0),               // 7: zke.agent.v1.ResultCode
}
var file_api_agent_v1_watch_proto_depIdxs = []int32{
	6, // 0: zke.agent.v1.ResourceWatchRequest.resource:type_name -> zke.agent.v1.GroupVersionResource
	7, // 1: zke.agent.v1.ResourceWatchResponse.result:type_name -> zke.agent.v1.ResultCode
	0, // 2: zke.agent.v1.ResourceWatchEvent.type:type_name -> zke.agent.v1.ResourceWatchEventType
	7, // 3: zke.agent.v1.ResourceWatchTrailer.result:type_name -> zke.agent.v1.ResultCode
	3, // 4: zke.agent.v1.ResourceWatchFrame.event:type_name -> zke.agent.v1.ResourceWatchEvent
	4, // 5: zke.agent.v1.ResourceWatchFrame.trailer:type_name -> zke.agent.v1.ResourceWatchTrailer
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_agent_v1_watch_proto_init() }
func file_api_agent_v1_watch_proto_init() {
	if File_api_agent_v1_watch_proto != nil {
		return
	}
	file_api_agent_v1_resource_proto_init()
	file_api_agent_v1_stream_proto_init()
	file_api_agent_v1_watch_proto_msgTypes[4].OneofWrappers = []any{
		(*ResourceWatchFrame_Event)(nil),
		(*ResourceWatchFrame_Trailer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_watch_proto_rawDesc), len(file_api_agent_v1_watch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agent_v1_watch_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_watch_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_watch_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_watch_proto_msgTypes,
	}.Build()
	File_api_agent_v1_watch_proto = out.File
	file_api_agent_v1_watch_proto_goTypes = nil
	file_api_agent_v1_watch_proto_depIdxs = nil
}
